### ISSUE TITLE
1.6.x Iteration Feedback

### ISSUE THREAD

**Issue by ArrayZoneYour** [leecade/react-native-swiper#1001]
We plan to solve the backlog of issues and PRs now. Welcome to install and feedback👏

```shell
npm i --save react-native-swiper@next
# Remember to clean old node_modules and restart the react-native dev server if you use 1.5.x before
```

## 💥 Breaking Changes 

android swiper container style props name change: `style` => `containerStyle`

### Dependency

* Remove ViewPagerAndroid, use ScrollView #1009 

### TypeScript

* correct the wrong types #1000 
* Add missing scrollBy TypeScript definition #931
* SwiperProps extends ScrollView base type (✨v1.6.0-rc.3)

### New Feature

* add scrollTo #831 
* Added prop to disable the PrevButton #749 
* Optionally render page #1004 

### Bug Fix

* ES6 and CommonJS compatibility #717 
* Solves the issue of state messing up when parent component calls setState #939 
* replay when autoplay is setted to true #1002 
* rename unsafe lifecycles to fix #1061 
* fix broken examples and migrate to react-native 0.60.x
* fix bad jumping on ios when loadMinimal set true
* fix fliker when loop and loadMinimal are enabled #1062 
* invoke onMomentumScrollEnd even offset no diff (✨v1.6.0-rc.3)

**Comment by confidence68** [comment]
Is it solve the problem  https://github.com/leecade/react-native-swiper/issues/957 ?

**Comment by mshepherd423** [comment]
Hey! I installed nightly version but it doesn't swipe anymore.. neither @1.5.6 for me at least.

I'm currently using :
react-native-swiper@1.5.13 (this is the one working for me, but with the ViewPagerAndroid warning)
react-native@0.59.9
OS: Android 9

**Comment by ArrayZoneYour** [comment]
> Hey! I installed nightly version but it doesn't swipe anymore.. neither @1.5.6 for me at least.
> 
> I'm currently using :
> react-native-swiper@1.5.13 (this is the one working for me, but with the ViewPagerAndroid warning)
> react-native@0.59.9
> OS: Android 9

You should open another issue to report it : )
I cannot reproduce it with the lack of information : (

**Comment by ithustle** [comment]
Refactoring some piece of code, in case, from `componentWillReceiveProps` to use `getDerivedStateFromProps` and `componentWillUpdate` to `componentDidUpdate` instead

**Comment by ArrayZoneYour** [comment]
@ithustle I plan to do it this weekend : )

**Comment by saadsaleem187** [comment]
react-native-swiper working fine on android but not on ios. On ios previous button is not working and also index number is causing problems. I don't know what's the problem with this package because 1.5 version works fine on ios but not on android and now latest version works fine on android but not on ios.

**Comment by saadsaleem187** [comment]
i don't know how you guys managing this package. Without testing why you uploaded new versions. So many issues with this package. 1.5 works on ios not on android and now latest version works fine on android without any issues but not on ios. This package is not stable.

**Comment by ursNj** [comment]
swipe is not working with latest react-native version 0.61.1

**Comment by ArrayZoneYour** [comment]
@saadsaleem187  Sorry for the bad experience, but I think you should open a separate issue and  only the link referenced here to help other contributors to solve it.

**Comment by alex2wong** [comment]
> swipe is not working with latest react-native version 0.61.1

Swiper is working fine in my IOS device:
"react": "16.9.0",
"react-native": "0.61.2",
"react-native-swiper": "^1.5.14",


btw, @ArrayZoneYour , we're looking forward the #1061 fix. Thanks a lot

**Comment by alex2wong** [comment]
emm, is it possible that we **patch a version** only include simple fix like #1061 ?  Since it would not bring much side-effect and unstable code. You know many guys are asking this fix brought by React upgrade : )

**Comment by juanjsebgarcia** [comment]
React Native 0.61.2 Android builds (not tested iOS) swiper refuses to swipe. This includes using the  `scrollBy()` commands. Interestingly the `showsPagination` dots do update but the content remains frozen. Has made the package completely unusable :(

I'll be digging in shortly to see if I can identify the issue

**Comment by ArrayZoneYour** [comment]
> React Native 0.61.2 Android builds (not tested iOS) swiper refuses to swipe. This includes using the `scrollBy()` func. Interestingly the `showsPagination` dots do update but the content remains frozen. Has made the package completely unusable :(
> 
> I'll be digging in shortly to see if I can identify the issue
> 
> Edit: What was the rationale behind removing `ViewPagerAndroid` and not simply sourcing it from its new home `import ViewPager from '@react-native-community/viewpager'`?

@juanjsebgarcia You'd better open an issue to provide more information.

**Comment by S-Vlad** [comment]
> Edit: What was the rationale behind removing `ViewPagerAndroid` and not simply sourcing it from its new home `import ViewPager from '@react-native-community/viewpager'`?

There is a version, that contains updated ViewPager: https://www.npmjs.com/package/react-native-swiper/v/1.6.0-dev.1

**Comment by fungilation** [comment]
Why remove when https://github.com/react-native-community/react-native-viewpager provides exactly the use case for paging through views, and offers best native performance?

**Comment by jantongiovanni** [comment]
This is still broken on Android. I am using it as a fullpage swipe and all nested ScrollViews do not work inside of the Swiper, but behave fine on iOS

**Comment by Aryojaam** [comment]
I am experiencing a huge performance loss upgrading from `1.5.14` to `1.6.0-rc.3`. By swiping the page, the index gets updated almost a second later. I am using redux as a state holder

**Comment by fungilation** [comment]
Removing `@react-native-community/viewpager` is honestly a mistake. If 1.6.x stays the course with removal, I for one will be forking 1.5.x to stay with viewpager for 100% native animation performance. Swiper is a key component to my entire app's UI, full screen so I need animation performance to be lag-free.

**Comment by juanjsebgarcia** [comment]
I have a fork with view pager added back into the 1.5.13 release which is working for me.
github.com/juanjsebgarcia/react-native-swiper#add-view-pager-to-1-5-13-release
