### ISSUE TITLE
Optionally render page

### ISSUE THREAD

**Issue by skizzo** [leecade/react-native-swiper#1004]
### Which OS ?

iOS & Android, doesn't matter.

### Version

- react-native-swiper `v1.5.13` & `v1.6.0@nightly.1`
- react-native `v0.57.8`

### Expected behaviour

A page that should be optionally rendered doesn't show up at all and reduces the total amount of pages to *one less than if optional page is rendered*.

### Actual behaviour

An empty page is shown, but the slide should be skipped completely.

### Steps to reproduce

```
<Swiper {...swiperProps}>

  <View style={stylePage}>
    <Text>Page 1 (always)</Text>
  </View>

  <View style={stylePage}>
    <Text>Page 2 (always)</Text>
  </View>

  { renderPage3 && // if this is set to "false", an empty page is shown
    <View style={stylePage}>
      <Text>Page 3 (optional)</Text>
    </View>
  } 

  <View style={stylePage}>
    <Text>Page 4 (always)</Text>
  </View>

</Swiper>
```

**Comment by ArrayZoneYour** [comment]
Can you reproduce it on v1.6.0@nightly.1 ?

**Comment by skizzo** [comment]
Yup, same thing with with `v1.6.0@nightly.1`.

**Comment by ArrayZoneYour** [comment]
Please provider the gif and the code with full example code (with stylePage, swiperProps)

I will investigate it soon :)

**Comment by skizzo** [comment]
It makes no difference what props I put, the issue can be reproduced with the exact code I posted originally. Also, I'm sure you can imagine what an "empty page" looks like without adding a gif ;)

```
const stylePage = {
  flex: 1, 
  alignItems: "center", 
  justifyContent: "center", 
}
```

Thanks for investigating!

**Comment by ArrayZoneYour** [comment]
@skizzo  It is a missing feature, I will try to support it in this week : )

**Comment by skizzo** [comment]
You the man, thanks a lot!

**Comment by ArrayZoneYour** [comment]
@skizzo You can test it on react-native-swiper@1.6.0-dev.1 👀

**Comment by skizzo** [comment]
Thanks, but it's still showing an empty page..

**Comment by ArrayZoneYour** [comment]
🤔Are you installing the new version?
![Screen Recording 2019-07-04 at 8 15 35 PM 2019-07-04 20_17_48](https://user-images.githubusercontent.com/21001457/60666151-f4282500-9e98-11e9-93f7-dac1814f377a.gif)

**Comment by skizzo** [comment]
My bad, my `npm install` didn't properly update the package. It works like a charm, thanks so much!

**Comment by ArrayZoneYour** [comment]
The logic of updating the current index also has some problem (when the index of the page which you want to remove is less than current index ), I will fix it in next nightly version.😄
