### ISSUE TITLE
Swiping or scrolling doesn't work

### ISSUE THREAD

**Issue by corasan** [leecade/react-native-swiper#1022]
### Version
Which versions are you using:

- react-native-swiper v? Tried 1.6 and 1.5.14, same issue.
- react-native v0.?.? 59.10

### Expected behaviour
To swipe when I swipe or scroll to next view when click on the next button.

### Actual behaviour
Doesn't scroll or swipe.

### How to reproduce it>
To help us, please fork this component, modify one example in examples folder to reproduce your issue and include link here.
-

### Steps to reproduce
1. Create Swiper component with views
2. Swipe or enable `showsButtons` and try to go to the next view
3.

Here is a sample of my code:

```
<Swiper
    style={{ height: 260, width: '100%' }}
    index={index}
    onIndexChanged={setIndex}
    scrollEnabled
    loop={false}
    showsButtons
>
    <View style={{ flex: 1, backgroundColor: 'red' }} />
    <View style={{ flex: 1, backgroundColor: 'blue' }} />
    <View style={{ flex: 1, backgroundColor: 'green' }} />
</Swiper>
```

**Comment by corasan** [comment]
Seems like the issue is caused by setting the `width`

**Comment by harshit8398** [comment]
+1
Does not work even with no custom width.
