### ISSUE TITLE
"Autoplay" has collapsed ，Very serious

### ISSUE THREAD

**Issue by ngxu** [leecade/react-native-swiper#1024]
![1564381807123](https://user-images.githubusercontent.com/43433064/62026878-d6877a80-b20e-11e9-9e6e-5e4d87d0bee4.gif)

Entering the page will not automatically play, you need to slide once, and then crash.
I tried to change the value of "autoplayTimeout" and it didn't work. The results were the same.

"react-native": "0.59.8",
"react-native-swiper": "^1.5.14",

**Comment by ngxu** [comment]
`<Swiper
          height={150}
          width={width*0.9} 
          showsButtons={false}
          showsPagination={true}
          loop={true}
          autoplay={true}
          // onMomentumScrollEnd={(e, state, context) => console.log('index:', state.index)}
          dot={<View style={{backgroundColor: 'rgba(0,0,0,.2)', width: 5, height: 5, borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3}} />}
          activeDot={<View style={{backgroundColor: '#000', width: 8, height: 8, borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3}} />}
          paginationStyle={{
            bottom: -23, left: null, right: 10
          }}
        >
        {this._renderItem()}
          {/* <View >
            <Text >Hello Swiper</Text>
          </View>
          <View >
            <Text >Beautiful</Text>
          </View>
          <View >
            <Text >And simple</Text>
          </View> */}
      </Swiper>`

This is my code.
Who can help me? Thank you very much.

**Comment by ngxu** [comment]
`
       <Swiper
          height={150}
          width={width*0.9} 
          showsButtons={false}
          showsPagination={true}
          loop={true}
          autoplay={true}
          // onMomentumScrollEnd={(e, state, context) => console.log('index:', state.index)}
          dot={<View style={{backgroundColor: 'rgba(0,0,0,.2)', width: 5, height: 5, borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3}} />}
          activeDot={<View style={{backgroundColor: '#000', width: 8, height: 8, borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3}} />}
          paginationStyle={{
            bottom: -23, left: null, right: 10
          }}
        >
        {this._renderItem()}
          {/* <View >
            <Text >Hello Swiper</Text>
          </View>
          <View >
            <Text >Beautiful</Text>
          </View>
          <View >
            <Text >And simple</Text>
          </View> */}
      </Swiper>
       
`
This is my code.
Who can help me? Thank you very much.

**Comment by ngxu** [comment]
```
 <Swiper
          height={150}
          width={width*0.9} 
          showsButtons={false}
          showsPagination={true}
          loop={true}
          autoplay={true}
          // onMomentumScrollEnd={(e, state, context) => console.log('index:', state.index)}
          dot={<View style={{backgroundColor: 'rgba(0,0,0,.2)', width: 5, height: 5, borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3}} />}
          activeDot={<View style={{backgroundColor: '#000', width: 8, height: 8, borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3}} />}
          paginationStyle={{
            bottom: -23, left: null, right: 10
          }}
        >
        {this._renderItem()}
          {/* <View >
            <Text >Hello Swiper</Text>
          </View>
          <View >
            <Text >Beautiful</Text>
          </View>
          <View >
            <Text >And simple</Text>
          </View> */}
      </Swiper>
```

This is my code.
Who can help me? Thank you very much.

**Comment by ngxu** [comment]
This problem has been solved:

  Update to  1.6.0-nightly

**Comment by ngxu** [comment]
The reason I found the problem was not the version, but the debug that opened the browser. When I shut down debug, that's not going to happen.
Have I been the only one who has ever encountered this problem? Have you not?

**Comment by moneyBreak** [comment]
It is my problem ,too. Thank you very much!
