### ISSUE TITLE
(Android) Bug When Swipe Pages

### ISSUE THREAD

**Issue by danielgssp** [leecade/react-native-swiper#1038]
### Which OS ?
Android 

### Version
Which versions are you using:

- react-native-swiper v?
1.6.0-nightly.3

- react-native v0.?.?
0.59.9

### Actual behaviour
I write an example

my swiper ...
```
<View style={styles.container}>
                <Swiper
                    loop={false}
                    showsPagination={false}
                    ref={ref => (this._swiper = ref)}
                    onTouchEnd={() => (this.inMotion = false)}
                    onTouchStart={() => (this.inMotion = true)}
                    onMomentumScrollEnd={() => (this.inMotion = false)}
                >
                    <Text> Page 1 </Text>
                    <Text>Page 2 </Text>
                </Swiper>
</View>
```

When I swipe to page 2 and then back to page 1 it shows me page 2 but the index is still page 1.
 I enabled the` loop = {true} `and this bug stopped, but when I disable the `loop` it happens = / plz can help me?

iOs still normal it doesn't happen!

reproduction
![GIF 01](https://user-images.githubusercontent.com/33849694/62787386-fdf60700-ba9a-11e9-9ceb-dbff41426fa9.gif)

**Comment by danielgssp** [comment]
![DEMO 01](https://user-images.githubusercontent.com/33849694/62787071-46f98b80-ba9a-11e9-8b3b-6039dd4cbd6a.gif)

**Comment by Sotatek-HieuDuong** [comment]
i have same issue :(

**Comment by yurkagon** [comment]
We can temporary use 1.5.14 version that works fine on android

**Comment by SDxBacon** [comment]
I got same issue here with 1.6.0-nightly.3. @danielgssp how did you solve this issue? Downgrading version back to 1.5.14 as yurkagon said?
