### ISSUE TITLE
Reset current component when view is active?

### ISSUE THREAD

**Issue by lindesvard** [leecade/react-native-swiper#104]
Hi, im building an app where I have 3 slides.

```
<Swiper style={styles.wrapper}>
    <View style={styles.slider}>
        <ListView/>
    </View>
    <View style={styles.slider}>
        <Wizard/>
    </View>
    <View style={styles.slider}>
        Another Slidw
    </View>
</Swiper>
```

My wizard component has 5 steps. I have a state (step) in the wizard component so I know where the user are. But if they do 2-3 steps and then swipe to a new slide and then back again to the wizard I want to reset that component and bring back everything to step 1.

I thought I could reset the state with componentDidMount in the Wizard. But obviously not :see_no_evil: 

So my question. What is the best way to say to my Wizard component. "Hey, you are active now! Reset all stuff and show step number 1"? Sorry if this is a stupid question but Im in my early stages of react and react-native.

**Comment by lrettig** [comment]
Hi @lindesvard 

You can probably achieve what you need by hooking into the [ScrollResponder methods](https://github.com/leecade/react-native-swiper#supported-scrollresponder), and passing state into your `Wizard` component as a prop, e.g.

```
var swiper = React.createClass({
  getInitialState() {
    return {index: 0};
  },
  _onMomentumScrollEnd(e, state, context) {
    this.setState({index: context.index});
  },
  render() {
    return (
      <Swiper style={styles.wrapper}
      onMomentumScrollEnd ={this._onMomentumScrollEnd}>
     ...
      <View style={styles.slider}>
          <Wizard swiperIndex={this.state.index}/>
      </View>
     ...
      </Swiper>
    )
  }
})
```

You could keep track of `swiperIndex` inside the wizard and reset to the first screen when it changes.
