### ISSUE TITLE
scrollTo(y,x,animated) is deprecated

### ISSUE THREAD

**Issue by xpmike** [leecade/react-native-swiper#106]
![20160315143715](https://cloud.githubusercontent.com/assets/1314128/13769557/728d7e76-eabb-11e5-9133-343fc5e04a43.png)

**Comment by lrettig** [comment]
+1

**Comment by lrettig** [comment]
This is a duplicate of https://github.com/leecade/react-native-swiper/issues/95

**Comment by Kennytian** [comment]
+1

**Comment by xpmike** [comment]
@lrettig tku for your remind

**Comment by Cspeisman** [comment]
#113 will fix this issue. For a temporary fix change file locally and run `npm start` to build.

**Comment by rajkissu** [comment]
Fixed in #112
