### ISSUE TITLE
react-native-swiper@1.6.0-nightly swipe not working and warnings

### ISSUE THREAD

**Issue by devilabhi** [leecade/react-native-swiper#1061]
I am facing issue in both android and iOS both

Which versions are you using: iphone 7 and android Nougat version

react-native-swiper version react-native-swiper@1.6.0

react-native version react-native@0.60.5

I also got warning i.e _componentWillUpdate is deprecated_ and _componentWillReceiveProps is deprecated_

Code I used is 

```
<View>
    <Swiper style={styles.wrapper} showsButtons={true}>
        <View style={styles.slide1}>
          <Text style={styles.text}>Hello Swiper</Text>
        </View>
        <View style={styles.slide2}>
          <Text style={styles.text}>Beautiful</Text>
        </View>
        <View style={styles.slide3}>
          <Text style={styles.text}>And simple</Text>
        </View>
    </Swiper>
</View>

export default HomeScreen;
```

**Comment by ArrayZoneYour** [comment]
fixed in v1.6.0-nightly.5
