### ISSUE TITLE
Swiper fliker when loop and loadMinimal are enabled

### ISSUE THREAD

**Issue by luiscerqueira** [leecade/react-native-swiper#1062]
When setting the loop mode and loadMinimal to true, the component flickers when swipping from the last item to the first, or from the first to the last (currently using images as items).

### Which OS ?
Android

### Version
- react-native-swiper v1.5.14
- react-native v0.59.0

### Expected behaviour
Expect the component to changes from items smoothly.

### Actual behaviour
The items are flickering

### How to reproduce it>
To help us, please fork this component, modify one example in examples folder to reproduce your issue and include link here.
-

### Steps to reproduce
1. Create a react-native-swiper with n children images components
2. Set loop and loadMinimal props to true
2. Swipe from the first to the last component of the swiper.
3. Swipe from the last to the first component of the swiper.
4. The component will flicker, like he is unmounting the visible items, and mounting again.

**Comment by ArrayZoneYour** [comment]
I prevent the first and last elements' unmount now. 
However, the component will still flicker on Android. The reason maybe you swipe the last to first, the event happened like below is not fast enough: 

Before flicker:
[4, 0, 1, 2, 3, 4, 0]
                          👆
After flicker:
[4, 0, 1, 2, 3, 4, 0]
     👆
