### ISSUE TITLE
swiper is displayed only after swiping

### ISSUE THREAD

**Issue by Jendyy** [leecade/react-native-swiper#1064]
mac os

- react-native-swiper v1.5.14
- react-native v0.50.4

Expected behaviour
the slider is displayed on the page

Actual behaviour
the swiper is displayed only after swiping (it does not matter which way)

### How to reproduce it>
when you first open the application everything is ok
further in the application I exit my profile and log into it
and when I open the page where the swiper is located I see an empty place. if I swipe the screen the swiper immediately appears and no longer disappears (until I exit my profile again)
tried to enter different users
-
### Steps to reproduce
1.open app
2.log out
3.login

my code
<img width="416" alt="Screenshot 2019-09-18 at 17 00 10" src="https://user-images.githubusercontent.com/50834021/65155344-cda86d80-da35-11e9-8f18-05bf8dae5832.png">

when i just opened the page
<img width="264" alt="Screenshot 2019-09-18 at 17 00 53" src="https://user-images.githubusercontent.com/50834021/65155484-0ba59180-da36-11e9-89fb-45294371650d.png">

swiped across the screen
<img width="267" alt="Screenshot 2019-09-18 at 17 01 07" src="https://user-images.githubusercontent.com/50834021/65155485-0c3e2800-da36-11e9-8c91-8a4d23183237.png">

**Comment by fega** [comment]
Having a similar issue here

**Comment by halfapple** [comment]
+1 on ios

**Comment by abeeralshaer** [comment]
Have you tried this? https://github.com/leecade/react-native-swiper/issues/906#issuecomment-449013745

**Comment by GauthierG** [comment]
I had the same issue and the solution with key={Date.now()} didn't work for me. I needed to add removeClippedSubviews={false} to fix this (but I don't understand why).

**Comment by Jendyy** [comment]
Hi @GauthierG @abeeralshaer 
the solution with key={Date.now()} didn't work for me too
removeClippedSubviews = {false} solved the problem
Thanks!

**Comment by abeeralshaer** [comment]
@Jendyy 
Me either. But my problem was totally different. The problem was that the swiper doesn't update after re-rendering. So I had to put the key something that changes like email/ which first is undefined then comes as a string.

**Comment by 77TecShaeer** [comment]
++
