### ISSUE TITLE
How do I install nightly version?

### ISSUE THREAD

**Issue by edoantonioco** [leecade/react-native-swiper#1072]
I want to install 1.6.0-nightly version

So I tried
npm install --save react-native-swiper@1.6.0-nightly
 and also
npm install --save react-native-swiper@1.6.0

and both fails, so whats the correct way?

**Comment by edoantonioco** [comment]
its 1.6.0-nightly.5
thanks to this
npm view react-native-swiper versions

closed

**Comment by tochukwu62** [comment]
do
 yarn add react-native-swiper@1.6.0-nightly
