### ISSUE TITLE
v1.6.0-rc.1: slider doesn't work

### ISSUE THREAD

**Issue by borgogelli** [leecade/react-native-swiper#1080]
I have migrated to the v1.6.0-rc.1 and the result is **dreadful**:

- slider autoply doesn't work, it shows only the last image
- drag to scroll doesn't work

(tested on both Android and iOS)

**Comment by ArrayZoneYour** [comment]
Can you provide an example for me to reproduce?

**Comment by ArrayZoneYour** [comment]
@borgogelli I setup a minimal usecase in the commit above. It works well and pass the test, you can provide the bad case you meet.

**Comment by borgogelli** [comment]
Here the a demo app: https://github.com/iubar/slider-test

**Comment by borgogelli** [comment]
Here the snack: 

https://snack.expo.io/@git/github.com/iubar/slider-test

You can see that the web version works fine while the android once (expo managed) doesn't work as expected (the same on the iOS)

**Comment by ArrayZoneYour** [comment]
@borgogelli 
https://github.com/iubar/slider-test/blob/master/ProductSlider1.js#L61 style => containerStyle

**Comment by borgogelli** [comment]
But is not the same of https://github.com/leecade/react-native-swiper/blob/master/examples/components/Basic/index.js#L36 ?

**Comment by ArrayZoneYour** [comment]
> But is not the same of https://github.com/leecade/react-native-swiper/blob/master/examples/components/Basic/index.js#L36 ?

The `style` is used on each page, and use empty style won't have effect

**Comment by borgogelli** [comment]
Thank you very much
