### ISSUE TITLE
给StyleSheet的 wrapper设置高度就出现问题

### ISSUE THREAD

**Issue by EasonQwQ** [leecade/react-native-swiper#1097]
### Which OS ?
ios 
### Version
Which versions are you using:
 react-native-swipe v1.5.14
- react-native-swiper v?
- react-native v0.?.?

### Expected behaviour
希望能滑动

### Actual behaviour
按照你们的新手教程，示例，但是一旦在给StyleSheet的 wrapper: {
    // height: 200,
    // width
  },设置了高度，就不能滑动，或者滑动有问题，请问为什么会这样呢？

**Comment by ArrayZoneYour** [comment]
I recommend you use v1.6.0-rc.3 and you can set the height of swiper as the example below
https://github.com/leecade/react-native-swiper/blob/develop/examples/components/Swiper/index.js

**Comment by tibic** [comment]
我也有这个问题

    "react-native-swiper": "^1.5.14",

**Comment by EasonQwQ** [comment]
:)
