### ISSUE TITLE
Allow a prop to change the color of the active dot.

### ISSUE THREAD

**Issue by cgarvis** [leecade/react-native-swiper#11]

**Comment by leecade** [comment]
hi @cgarvis 

The prop `dot` / `activeDot` maybe is what's your need.

```jsx
<Swiper 
dot={<View style={{backgroundColor:'rgba(0,0,0,.2)', width: 5, height: 5,borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3,}} />}
          activeDot={<View style={{backgroundColor: '#000', width: 8, height: 8, borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3,}} />}
>
```

See how to use in example: https://github.com/leecade/react-native-swiper/blob/master/examples/examples/swiper.js#L64

**Comment by cgarvis** [comment]
This is what I ended up doing.  I had to dig into the code to pull out the default dot styles and change just the color.  I can see this being the most changed attribute, so why not make it easy.

 ```html
<Swiper dotColor="#000" activeDotColor="red" />
```

**Comment by leecade** [comment]
I see, I consider that someone need to change the `size`  `postion` or something else.
As you said, maybe a shortcut prop to do this is a better way
And would u like send a PR for this feature, or I will do it later

**Comment by denizs** [comment]
I completely agree with @cgarvis. I guess this ist the most changed attribute by far.
Would you mind me making a pull request?
Best,
D

**Comment by leecade** [comment]
@denizs  PR is welcome

**Comment by denizs** [comment]
Pr is in! #298
