### ISSUE TITLE
Getting ViewPagerAndroid error in letest virsion.

### ISSUE THREAD

**Issue by InfoAjay** [leecade/react-native-swiper#1112]
### Which OS ?
Android

### Version
Which versions are you using:

- react-native-swiper: ^1.6.0-nightly.5
- react-native: 0.61.1

### Expected behaviour
react-native-swiper should run normally

### Actual behaviour
Getting error of "ViewPagerAndroid has been removed from React Native. It can now be installed and imported from 'react-native-viewpager' instead of 'react-native'."
![Image of Error](https://i.imgur.com/PD1adIz.png)

### Steps to reproduce
1. Create new project of react native.
2. Add library using "**npm i --save react-native-swiper@nightly**"
3. run app using "**react-native run-android.**"

**Comment by InfoAjay** [comment]
@leecade Are you watching this issue..??

**Comment by teamzz111** [comment]
@leecade this problem is **fixed**! #1116
