### ISSUE TITLE
Swiper cropped content

### ISSUE THREAD

**Issue by p4kaidu** [leecade/react-native-swiper#1126]
### Version
Which versions are you using:

- react-native-swiper v1.6.0-nightly.5
- react-native v0.61.5

### Expected behaviour
Normal scrolling without cropping
![image](https://user-images.githubusercontent.com/45810834/71570678-811a0700-2ae7-11ea-9ae7-5bdc64a25ab1.png)

### Actual behaviour
Inner view is cropped
![image](https://user-images.githubusercontent.com/45810834/71570681-86775180-2ae7-11ea-8a3a-c50372c1679d.png)

### How to reproduce it>
Wrap swiper in view and set to this view paddingLeft and paddingRight
### Steps to reproduce
1.
 ```
<View style={{paddingLeft:30,paddingRight:30}}>
 <Swiper>
 <View>
  <Text>123</Text>
 </View>
 <View>
  <Text>123</Text>
 </View>
 </Swiper>
</View>
```

**Comment by mishsom** [comment]
facing same issue, is there any fix for the same?

**Comment by anasalsaadi14** [comment]
+1 same here

**Comment by perceivxl** [comment]
Same I can't sem to find a solution

**Comment by meowcorp** [comment]
I believe that the problem is not in the component. This behavior is due to the fact that the container has a padding. In order to fix this, you should remove the padding from the container and add it to all internal views
