### ISSUE TITLE
warning:  Use `scrollTo({x: 5, y: 5, animated: true})` instead.

### ISSUE THREAD

**Issue by ensorrow** [leecade/react-native-swiper#118]
It keeps showing 'warning: JavaScript] `scrollTo(y, x, animated)` is deprecated. Use `scrollTo({x: 5, y: 5, animated: true})` instead.' after I upgrade to rn 0.22.0. I hope you can fix this problem.

**Comment by XiSmartElf** [comment]
so what's the status of the fix?

**Comment by huazhiyuan2008** [comment]
![image](https://cloud.githubusercontent.com/assets/2877748/14593210/3a045e94-055a-11e6-8bc6-7d13c99a012a.png)
React Native 0.23.1

**Comment by rajkissu** [comment]
Fixed in #112
