### ISSUE TITLE
 Does not scroll automatically and images are repeated when using axios

### ISSUE THREAD

**Issue by julianlujan1** [leecade/react-native-swiper#1187]
### Which OS ?
iOS & Android
### Version
Which versions are you using:

- react-native-swiper 1.6.0
- react-native v 0.62 with Expo

### Expected behaviour

The expected behavior is that the banner is automatically scrolled with the information obtained when consuming an API with Axios

### Actual behaviour

It does not scroll automatically and it is evident that images are repeated when manually scrolling

### How to reproduce it>
attached code
```
import React, { useEffect, useState, Component } from "react";
import { Image, StyleSheet, Dimensions, View, ScrollView } from "react-native";
import Swiper from "react-native-swiper";
import { axiosClient } from "../../../config/axios";

var { height, width } = Dimensions.get("window");


export default function Banners() {
  const [banners, setBanners] = useState([]);

  useEffect(() => {
    axiosClient
      .get("/service/banner_available")
      .then(function (response) {
        setBanners(response.data);
      })
      .catch(function (error) {});
  }, []);

  return (
    <View>
      <ScrollView>
        <View style={{ flex: 1, marginTop: 30 }}>
          <View style={{ alignItems: "center" }}>
            <Swiper
              style={{ height: width / 2 - 50 }}
              autoplay
              autoplayTimeout={4}
            >
              {banners.map((item, i) => (
                <Image
                  key={i}
                  style={styles.imageBanner}
                  source={{ uri: item.imagePath }}
                ></Image>
              ))}
            </Swiper>
          </View>
        </View>
        <View style={{ height: 20 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  imageBanner: {
    height: width / 4,
    width: width - 40,
    borderRadius: 20,
    marginHorizontal: 20,
  },
});
```

When I create an array constant with fake data and pass it to the useState, it works, but when the data is fetched by axios it doesn't work correctly.

**I clarify the following:**
When the data is obtained by axios, in the app if the api images are loaded, what it does not do is the automatic scroll that I have and it duplicates some images. So I think the problem is when used in conjunction with Axios.

**Comment by julianlujan1** [comment]
> Android & iOS

**Comment by rafaelsilvestre** [comment]
I have the same problem, after searching as information via API, the points do not work.

**Comment by julianlujan1** [comment]
@rafaelsilvestre have you been able to find any solution?

**Comment by rafaelsilvestre** [comment]
> @rafaelsilvestre você conseguiu encontrar alguma solução?

Only one check was made to render the Swiper component, only when my array is not empty.

**Comment by julianlujan1** [comment]
@rafaelsilvestre Thanks for answering,
Could you share some code with me about how you solved it?

**Comment by rafaelsilvestre** [comment]
> @rafaelsilvestre Thanks for answering,
> Could you share some code with me about how you solved it?

![image](https://user-images.githubusercontent.com/6759605/84531704-5994b080-acbb-11ea-8378-848155c20110.png)

In my case, this verification resolved

**Comment by julianlujan1** [comment]
@rafaelsilvestre Yesterday I implemented a similar solution and I was also successful! Thanks buddy for putting light on the road.
