### ISSUE TITLE
First image of the slider flickers when autoplay and loop is set to true

### ISSUE THREAD

**Issue by ajitdas123** [leecade/react-native-swiper#1232]
### Which OS ?
Android,  haven't tasted on IOS yet

### Version
Which versions are you using:

- react-native-swiper v1.6.0
- react-native v0.63.2

### Expected behaviour

Expected the animation to be smooth when coming back to the first slide

### Actual behaviour
But its flicker once when returning to the first slide 

### How to reproduce it>
To help us, please fork this component, modify one example in examples folder to reproduce your issue and include link here.

I used the example code
- https://github.com/leecade/react-native-swiper/blob/master/examples/components/AutoPlay/index.tsx

Also attaching a GIF file for the same might take some time to load.

![newcropped](https://user-images.githubusercontent.com/20204881/94986197-5aa76180-057a-11eb-8ce4-5716f52fffef.gif)

**Comment by victoriomolina** [comment]
Try to set removeClippedSubviews to false.

```
     <RNSwiper
        autoplay
        loop
        removeClippedSubviews={false}
      >
```

That worked for me.

**Comment by ajitdas123** [comment]
Yes worked ty @VictorioMolina

**Comment by abuujurayj** [comment]
This is how i solved it, thanks to chatGPT.

                      import React, { Component } from 'react;
                      import Swiper from 'react-native-swiper';
     
                      class MySwiper extends Component {
                        
                        constructor(props: Props) {
                          super(props);
                      
                          this.state = {
                            index: 0,
                          };
                        }

                        shouldComponentUpdate(nextProps, nextState) {
                          // Only update if the current and next slide indexes are different
                          return this.props.index !== nextProps.index;
                        }
                      
                        render() {
                                return (
                                  <Swiper
                                    autoplay
                                    loop={true}
                                    index={this.props.index}
                                    removeClippedSubviews={false}
                                  >
                                    {/* Your slide components here */}
                                  </Swiper>
                                );
                        }
                      }

**Comment by ajitdas123** [comment]
@abuujurayj And what it has to do with chatGPT? How come it's any different than what is given by Victor?

**Comment by carlandren2002** [comment]
> Try to set removeClippedSubviews to false.
> 
> ```
>      <RNSwiper
>         autoplay
>         loop
>         removeClippedSubviews={false}
>       >
> ```
> 
> That worked for me.

Brilliant! Thanks
