### ISSUE TITLE
ListView Children repeating in loop

### ISSUE THREAD

**Issue by getnashty** [leecade/react-native-swiper#125]
My code looks like the following:

` <Swiper>`
`     <View><Text>... `
`     <View><Text>... `
`     <View><Text>... `
`     <View><Text>... `
`  </Swiper>`

It seems as though the content is totally out of order, and jumps around when I swipe.

Not really sure what I'm missing?

**Comment by getnashty** [comment]
This had to do with my onMomentumScrollEnd callback

**Comment by naveen-iyer-13** [comment]
@getnashty how did you fix this issue?
