### ISSUE TITLE
Persist taps outside of TextInput when keyboard open not working on iOS & Android

### ISSUE THREAD

**Issue by maxstudener** [leecade/react-native-swiper#1255]
### Which OS ?
iOS and Android but does work on web

### Version
Which versions are you using:

- react-native-swiper v1.6.0
- react-native v0.6.3

### Expected behavior
When I click a button outside of text input inside of the swiper it persists the tap(click).

### Actual behavior
Closes Keyboard and doesn't persist tap.

### How to reproduce it
https://snack.expo.io/LVnvOWzau

### Steps to reproduce
1. click text input, watch keyboard open
2. click "Next!"
3. watch it fail

**Comment by whitefang57** [comment]
adding `keyboardShouldPersistTaps='handled'` to the Swiper element fixes the issue for me

**Comment by maxstudener** [comment]
Adding It doesn't work inside the expo example, what am i missing?

**Comment by whitefang57** [comment]
I just had it working on iOS too
https://i.imgur.com/SKdojg3.gif

**Comment by maxstudener** [comment]
👍  updated my expo and it worked as well, might be worth adding to the readme

**Comment by whitefang57** [comment]
glad I could help! I've seen this issue before on ScrollView and thought the Swiper may have been built on top of something like that
