### ISSUE TITLE
when props change and render again，the swiper elements position move for no reason

### ISSUE THREAD

**Issue by renrenguiwei** [leecade/react-native-swiper#1266]
![image](https://user-images.githubusercontent.com/7834109/110423354-da15ff80-80db-11eb-8b70-da50caec202b.png)

**Comment by renrenguiwei** [comment]
Is there anyone can explain?

**Comment by GSolari79** [comment]
I face the same issue

**Comment by renrenguiwei** [comment]
Only occured in the ios simulator, android pixal simulator is good.

**Comment by renrenguiwei** [comment]
[Thank You!](https://github.com/leecade/react-native-swiper/issues/1175#issuecomment-635558672)

**Comment by renrenguiwei** [comment]
`loadMinimal={true} `seems to have fixed it for me. Hope it works for you!
[Thanks this guy!!!](https://github.com/leecade/react-native-swiper/issues/1175#issuecomment-635558672)

**Comment by wangqiannan** [comment]
> `loadMinimal={true} `seems to have fixed it for me. Hope it works for you! [Thanks this guy!!!](https://github.com/leecade/react-native-swiper/issues/1175#issuecomment-635558672)

thank you very much. It helps me a lot!

**Comment by Ritikkk-09** [comment]
In my case when i get props and set  index for active swiper screen  , index set in state but  swiper's method  "  onIndexChanged  "  is not working   what should i do ?
