### ISSUE TITLE
How to let the Swiper height suit the elements height

### ISSUE THREAD

**Issue by RickoNoNo3** [leecade/react-native-swiper#1288]
### Which OS ?
whatever

### Version
- react-native-swiper v1.6.0
- react-native v0.64.1

### Issue

The Swiper in my project is supposed to contain some children Views with unknown heights. And the height of the Swiper should be the max height of its children.
Is there somebody can solve this?

**Comment by tannusesquerdo** [comment]
I've managed to get this working with this code:

But, in this case, I received the height of each children by props.

```import { Animated } from 'react-native';
import Swiper from 'react-native-swiper';

const AnimatedSwiper = Animated.createAnimatedComponent(Swiper);

const Slider = ({ children }) => {
	const [current, setCurrent] = React.useState(0);
	const height = React.useRef(new Animated.Value(100)).current;

	React.useEffect(() => {
		Animated.timing(height, {
			useNativeDriver: false,
			toValue: children[current].props.height,
		}).start();
	}, [current]);

	return (
			<AnimatedSwiper
				height={height}
				onIndexChanged={(index) => setCurrent(index)}
				loop={false}
			>
				{children}
			</AnimatedSwiper>
	);
};

**Comment by RickoNoNo3** [comment]
@tannusesquerdo THX, I've found another solution in https://github.com/leecade/react-native-swiper/issues/1191#issuecomment-674992463 . It works by using `onLayout` event to listen and get the absolute height of the children and put it into Swiper style.
It is nice to mix it with your animations. I'll give a try.
