### ISSUE TITLE
deprecate issues

### ISSUE THREAD

**Issue by byk04712** [leecade/react-native-swiper#129]
`dis/index.js `
---
line 312   ` this.refs.scrollView && this.refs.scrollView.scrollTo(x, y);`

---
should update to 
line 312   ` this.refs.scrollView && this.refs.scrollView.scrollTo({x:x, y:y});`

**Comment by abhaytalreja** [comment]
+1

**Comment by jmaties** [comment]
+1

**Comment by rajkissu** [comment]
Fixed in #112
