### ISSUE TITLE
Warning in console about key prop for pagination

### ISSUE THREAD

**Issue by Benmidi** [leecade/react-native-swiper#13]
I noticed that the code that generates the dots is looping without a key prop on the <View> component which leads to this warning, no biggie just thought I would share.

"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of index. It was passed a child from SignDetail. See http://fb.me/react-warning-keys for more information."

**Comment by leecade** [comment]
hum, YES need a key prop, would you like seed me a PR?

**Comment by leecade** [comment]
fixed
