### ISSUE TITLE
ReactNative.createElement is deprecated.

### ISSUE THREAD

**Issue by ljunb** [leecade/react-native-swiper#138]
Here's a warning "ReactNative.createElement is deprecated. Use React.createElement from the 'react' package instead." when I'm using the version 1.4.3 in my project.

**Comment by fungilation** [comment]
Same warnings. This need fixing before deprecation becomes breaking error in RN 0.26.

**Comment by wangdaliu** [comment]
As the same, looking forward this fix

**Comment by shidhincr** [comment]
@leecade There is a PR #137 open to fix this issue. Could you please review ?

**Comment by rajkissu** [comment]
This has been fixed in PR #135
