### ISSUE TITLE
How can i make the responsive image based on device width ?

### ISSUE THREAD

**Issue by futurefeeling** [leecade/react-native-swiper#139]

**Comment by alkaha** [comment]
1. Add Dimensions component
import {
...
  Dimensions,
... 
} from 'react-native';

2. get the width/height
var {width, height} = Dimensions.get('window');

3. use width/height in styles
const styles = StyleSheet.create({
  wallpaperImage: {
  flex: 1,
  width: width,
  height: height,
  backgroundColor: '#000',
 }
});

**Comment by futurefeeling** [comment]
I got it, and i did it, thanks:)
