### ISSUE TITLE
Issue rendering dynamic data, stacked 'slides'

### ISSUE THREAD

**Issue by loreasinclaire** [leecade/react-native-swiper#14]
The swiper is working great for us when we create slides that contain static stuff:

i.e.
< swiper >
    < view >stuff< /view >
   < view >stuff< /view >
< view >stuff< /view >
< /swiper >

However, when we loop in dynamic content for the list of interior views like so:

< swiper >
    { slideLoop }
< /swiper >

all of the views render vertically stacked within the first 'slide', instead of each displaying as a slide as you'd expect. Has anyone experienced issues like this?

Thanks

**Comment by brianantonelli** [comment]
How did you solve this?

**Comment by apolkingg8** [comment]
@loreasinclaire I'm got same issue, can you share your solution?

**Comment by leoabacade** [comment]
ok, I got it working 
just change the componentDidMount to componentWillMount @ this.setState() for item[]

**Comment by iniestano8** [comment]
I'm got this issue,and i don't think this is a good solution @leoabacade

**Comment by leoabacade** [comment]
@iniestano8 , any suggestions are welcome.

**Comment by nguyendhse** [comment]
I just solved this problem by put <Swiper>....</Swiper> inside a ScrollView like this 
<ScrollView>
	<Swiper autoplay autoplayTimeout={4} height={248}>
		{popularMovies.results.map(movie => <MovieCard key={movie.id} movie={movie}/>)}
	</Swiper>
</ScrollView>

**Comment by KarlsDaddy** [comment]
@loreasinclaire I'm got same issue, can you share your solution?
