### ISSUE TITLE
iOS上当滑动很快时，滑到最后一页后继续滑，index可能不是整数

### ISSUE THREAD

**Issue by whlpkk** [leecade/react-native-swiper#140]
`
updateIndex: function updateIndex(offset, dir) {

    var state = this.state;
    var index = state.index;
    var diff = offset[dir] - state.offset[dir];
    var step = dir == 'x' ? state.width : state.height;

    // Do nothing if offset no change.
    if (!diff) return;

    // Note: if touch very very quickly and continuous,
    // the variation of `index` more than 1.
    index = index + diff / step;

    if (this.props.loop) {
      if (index <= -1) {
        index = state.total - 1;
        offset[dir] = step * state.total;
      } else if (index >= state.total) {
        index = 0;
        offset[dir] = step;
      }
    }

    if (Math.floor(index) !== index ) {
        //说明index不是整数
        return;
    }

    this.setState({
      index: index,
      offset: offset
    });
  }
`

updateIndex这个函数内部应该加上判断index是否是整数的判断吧？

**Comment by rajkissu** [comment]
The function now ensures the index is an integer via `parseInt()`. Closed.
