### ISSUE TITLE
Horizontal views stuck in between, index not whole numbers

### ISSUE THREAD

**Issue by fungilation** [leecade/react-native-swiper#141]
I'm creating an app with Swiper used in horizontal, with Views (wrapping normal Scrollviews) as children. So when swiping left/right, you get a sequence of 10 Views.

Problem is, once those Views are loaded with text in child scrollviews, swiping left/right rapidly sometimes result in views stuck between horizontally adjacent views. I've logged state of the Swiper component onMomentumScrollEnd, and state.index I see is 1.9999999999999991, 2.9999999999999991, etc. after this occurred.

This is pretty jarring on UX, and is a bug likely to affect other scenarios.

Not sure if I can easily post an exacting reproducible case, but am I the only one seeing this? Looks like #140 has similar issue with non-whole number index. (I know, he should type in English)

**Comment by rajkissu** [comment]
Fixed, closing.

**Comment by fungilation** [comment]
Will test after I get back in town but good stuff!
