### ISSUE TITLE
Compatibility width react ^0.26.0

### ISSUE THREAD

**Issue by awinogrodzki** [leecade/react-native-swiper#148]
Hello,

While using with react 0.26.0 I get error Cannot get property 'bool' of undefined which is caused by 0.20.0+ version of react. Do you plan on updating Swiper so it supports react v. 0.20.0+ ?

**Comment by jiafuzhang** [comment]
支持～加油～

**Comment by rajkissu** [comment]
Hi @awinogrodzki, I think you meant RN 0.26.0. Please try the latest commit from the repo, I've merged a PR to support RN 0.26.0
