### ISSUE TITLE
Callbacks for each slide

### ISSUE THREAD

**Issue by the4dpatrick** [leecade/react-native-swiper#15]
There should be away to execute code based on if you are currently on a certain slider. This could be a prop called `onView` or something that receives a callback function.

Use case:
There are multiple slides in the swiper. On the last slide, you can auto-focus on a text field at the same time `onMomentumScrollEnd` is called

**Comment by grabbou** [comment]
Can't you just use onMomentumScrollEnd? It receives an index of current slide, so there should not be any problem ;)
