### ISSUE TITLE
Can't work with RN0.26 

### ISSUE THREAD

**Issue by aksonov** [leecade/react-native-swiper#151]
Even latest master contains ReactNative.PropTypes and ReactNative.createClass...

**Comment by hasen6** [comment]
Really wanted to use this but its really not compatible with RN 0.25+

**Comment by rajkissu** [comment]
This has been fixed in #149

**Comment by hasen6** [comment]
Its been fixed? But I just downloaded it today and it didn't work.

**Comment by rajkissu** [comment]
The fix went through earlier, but the examples weren't updated. Try them now, I just pushed a commit to update the examples and have released v1.4.4 to npm.

**Comment by itinance** [comment]
On iOS, i get "Unable to resolve module ReactDefaultPerf" running the example. Yes, i did npm install before

**Comment by rajkissu** [comment]
@itinance RN issue, make sure you have React@15.0.2 installed: https://github.com/facebook/react-native/issues/7719
