### ISSUE TITLE
In android, the default page is the last child

### ISSUE THREAD

**Issue by zjhsd2007** [leecade/react-native-swiper#157]
hi,I used the example of documentation, but found the default page is the last child.and the set title property,can`t show.

**Comment by caofb** [comment]
same problem

**Comment by caofb** [comment]
@zjhsd2007,try set loop to false

**Comment by rajkissu** [comment]
This has been fixed and merged, please refer to #171

**Comment by zhiyingzzhou** [comment]
@rajkissu  is unless
