### ISSUE TITLE
Mutating props: attempted to assign to readonly property

### ISSUE THREAD

**Issue by joshhunt** [leecade/react-native-swiper#158]
Trying to use the Swiper component in react-native 0.26.2 in my iOS 9.3 simulator gives the error `attempted to assign to readonly property`

<img width="369" alt="error screenshot" src="https://cloud.githubusercontent.com/assets/46142/15572634/185fcd3e-2385-11e6-8cc8-1f432bd04bf6.png">

Which is tracked down to [this line](https://github.com/leecade/react-native-swiper/blob/d333010/src/index.js#L495) where you mutate `this.props` - something that probably shouldn't be done.

**Comment by rajkissu** [comment]
Fixed in #169
