### ISSUE TITLE
scrollTo method

### ISSUE THREAD

**Issue by ilansas** [leecade/react-native-swiper#17]
Hi, 

I looked into your code to use it with tabs, the `scrollTo(index)` method was great but is bugged. You should get rid of the `this.state.index` which has nothing to do here. This took me so much time to find the problem so I share it !

**Comment by MossP** [comment]
What bug were you addressing with this @ilansas? I've just come across a bug where attempting to scroll past the limits then clicking an action containing `scrollTo` fails. Is this the same thing?

**Comment by MossP** [comment]
I've opened an issue for it. If it's the same thing I'll close it. https://github.com/leecade/react-native-swiper/issues/41

**Comment by rajkissu** [comment]
Merged #87
