### ISSUE TITLE
Cannot install the module

### ISSUE THREAD

**Issue by Davidmeteor** [leecade/react-native-swiper#173]
Hi all,

I use the following installation command.

$ npm i react-native-swiper --save

Unfortunately, there is one compilation error when I build my xcode project. Do you know how to deal with it?

uncaught error Error: UnableToResolveError: Unable to resolve module react-native-swiper from /Users/david/Project/TEST/App/Dev/TEST/test/Operation.js: Invalid directory /Users/node_modules/react-native-swiper

Thanks!

**Comment by rajkissu** [comment]
Refer to https://github.com/facebook/react-native/issues/4968
