### ISSUE TITLE
<Swiper /> component wrapped in a ScrollView?

### ISSUE THREAD

**Issue by joshyhargreaves** [leecade/react-native-swiper#177]
Forgive me for creating noise in the midst of genuine issues, but I'm struggling a bit with something!

So I have three views within a Swiper component and I want to persist scroll position in those views. So if  I've scrolled halfway down a view in one view and I swipe to the right, I want to be able to swipe onto the same position in the next view (think paging through days in a calendar, you're looking at 6pm, you want to swipe onto 6pm on the adjacent day). 

I'm thinking I should be able to wrap a Swiper component in a ScrollView to achieve this. 

![image](https://cloud.githubusercontent.com/assets/1807207/16322231/92726ddc-3999-11e6-8beb-36e0b98711ef.png)

I am setting fixed height for the Swiper Component inside the ScrollView, but it's not quite working out!
I can't actually scroll without the view itself bouncing back!

If someone might have some insight on this, that'd be great :). 

Thanks.

**Comment by ChristianTucker** [comment]
Gonna bump this to the top, none of the touch inputs are sent to the component when wrapped in a ScrollView

**Comment by joshyhargreaves** [comment]
You can do something like this is you want to synchronise the scrollViews: https://gist.github.com/jevakallio/e95b8ee3c649eb64b2dc768be9375e11
