### ISSUE TITLE
TouchableOpacity in view not work

### ISSUE THREAD

**Issue by sunquanzhi** [leecade/react-native-swiper#190]
If add TouchableOpacity in view,it not work and the image not show.
CODE:  
<Swiper style={styles.wrapper} height={200}
         onMomentumScrollEnd={function(e, state, context){console.log('index:', state.index)}}
         dot={<View style={{backgroundColor:'rgba(0,0,0,.2)', width: 5, height: 5,borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3,}} />}
         activeDot={<View style={{backgroundColor: '#000', width: 8, height: 8, borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3,}} />}
         paginationStyle={{
           bottom: 0, left: null, right: 10,
         }} loop={true}>
          <View style={styles.slide} title={<Text numberOfLines={1}  style={{color: 'black',marginTop:-50}}>伊布加盟曼联</Text>}>
              <TouchableOpacity onPress={()=>{console.log('TouchableOpacity')}}>
             <Image style={styles.image} source={{uri: 'http://n.sinaimg.cn/sports/transform/20160702/hJN0-fxtsatm1191632.png'}} />
                </TouchableOpacity>
           </View>
           <View style={styles.slide} title={<Text numberOfLines={1} style={{color: 'black',marginTop:-50}}>Big lie behind Nine’s new show</Text>}>
             <Image style={styles.image} source={{uri: 'http://a.hiphotos.baidu.com/image/w%3D310/sign=4459912736a85edffa8cf822795509d8/bba1cd11728b4710417a05bbc1cec3fdfc032374.jpg'}} />
           </View>
           <View style={styles.slide} title={<Text numberOfLines={1}>Why Stone split from Garfield</Text>}>
             <Image style={styles.image} source={{uri: 'http://e.hiphotos.baidu.com/image/w%3D310/sign=9a8b4d497ed98d1076d40a30113eb807/0823dd54564e9258655f5d5b9e82d158ccbf4e18.jpg'}} />
           </View>
          
       </Swiper>

**Comment by sunquanzhi** [comment]
that's ok,I use the wrong method.

**Comment by Descartes310** [comment]
@brucesq  Hello, how did you solve this issue ?
I'm facing to the same one.
