### ISSUE TITLE
Loop with problems in android

### ISSUE THREAD

**Issue by pampang** [leecade/react-native-swiper#193]
Assume we have 3 pages, and we ard at index 0 page.

From index 0 to index 2:
[2]  <--scroll left--  [0],  works.

Then, from index 2 to index 1:
[1]  <--scroll left--  [2],  failed. 
We cannot scroll to left anymore.

**Comment by ZRZn** [comment]
I have the same question

**Comment by ZRZn** [comment]
and autoPlay doesn't work both in android and ios

**Comment by jasmo2** [comment]
I have the same problem, how do you solve it?
