### ISSUE TITLE
react-native-swiper in  react-native-scrollable-tab-view can,t show

### ISSUE THREAD

**Issue by yuanji123** [leecade/react-native-swiper#200]
where i put react-native-swiper  into  react-native-scrollable-tab-view,  the image can,t show, my react-native version is 0.28, how can i solve this.

![image](https://cloud.githubusercontent.com/assets/12931899/17136336/41832b54-5367-11e6-961f-967a15ffa8fd.png)

**Comment by yuanji123** [comment]
i found is not the problem of reac-native-scrollable-tab-view ,when i use react-native-swiper in listview renderHeader in android, the image can,t show

**Comment by aneesv** [comment]
Have similar issue, Image is not loading when used inside listview

**Comment by xiaomilii** [comment]
Have a same issue

**Comment by skx11500** [comment]
Have similar issue , i see the source code ,maybe use ViewPagerAndroid lead to this problem

**Comment by liuxisong** [comment]
Have similar issue, did anyone solve this?

**Comment by tasiyo7333** [comment]
Did you try to add prop 'removeClippedSubviews={false}' ?

<Swiper removeClippedSubviews={false}>
{this.props.children}
</Swiper>

removeClippedSubviews cause the same problem.

**Comment by habibridho** [comment]
I got the same problem when using this swiper and react-native-scrollable-tab-view. According to [this](https://github.com/skv-headless/react-native-scrollable-tab-view/issues/187) which is a quite similar case, there is a problem with the use of ViewPagerAndroid. So I try to find ViewPagerAndroid in the source file and replace it with Scrollview. And now it works like charm alongside react-native-scrollable-tab-view.

@leecade is there any particular reason in using ViewPagerAndroid?

**Comment by habibridho** [comment]
I found out that the workaround I mentioned above, messed up with the pagination.

I find another solution to integrate this swiper and react-native-scrollable-tab-view without messing the source file. I make another component that only render the swiper, then mount it in the main component.

**Comment by windhost** [comment]
I use the way mentioned by @habibridho , replace  ViewPagerAndroid by the Scrollview. The swiper show, but when I swipe to right after fifth time, the swipe can't be sliced again, what the problem.

**Comment by 438198602** [comment]
I also encountered the same problem。

**Comment by liuya891012** [comment]
<ListView
  removeClippedSubviews={false}
/>

**Comment by leecade** [comment]
@liuya891012 yes, scrollview won't render sub component outside of viewport for improve performance

**Comment by ammichael** [comment]
Guys, I'm having this same issue. I'm using a main a swiper inside a swiper. If I change something in the code and reload, it shows perfectly. Tried to set all ScrollView and Swiper removeClippedSubviews props to false, changed ViewPagerAndroid in source to ScrollView, but nothing works.

If I change to loop false and swap, the next image loads too.

Help? =(

![android-swiper-bug](https://cloud.githubusercontent.com/assets/6873880/19461698/90010964-94c5-11e6-9eee-584b92737bba.png)

**Comment by aqnaruto** [comment]
![image](https://cloud.githubusercontent.com/assets/9067159/20858085/2cd498ca-b977-11e6-8cd0-f188446a9c38.png)
![image](https://cloud.githubusercontent.com/assets/9067159/20858094/495f78ca-b977-11e6-959e-f7ff947eca2a.png)
still not work @liuya891012

**Comment by aqnaruto** [comment]
but nothing works +1 @ammichael

**Comment by qizhenshuai** [comment]
where add??

**Comment by woshi82** [comment]
yup, i have try this #311, and the problem solved.you can try this way selectively

**Comment by mah93** [comment]
react-native-scrollable-tab-view cause the problem,i have used another component to solved it

**Comment by huy-lv** [comment]
@mah93  which lib do you use?

**Comment by chudaotrucnhan** [comment]
find the index.js in node_modules\react-native-swiper\src. In the line 640 replace ViewPagerAndroid >> ScrollView. 
Comment onPageSelected={this.onScrollEnd} and add onMomentumScrollEnd={this.onScrollEnd}
Edit line 466: this.scrollView && this.scrollView[animated ? 'setPage' : 'setPageWithoutAnimation'](diff) >> this.scrollView && this.scrollView.scrollTo({ x, y, animated })
Sorry to arthur of react-native-swiper i just want to use it on android =.=

**Comment by HuXin957** [comment]
please add key={JSON.stringify(data)}  , retry

**Comment by skx11500** [comment]
收到
