### ISSUE TITLE
swipe only with the arrow

### ISSUE THREAD

**Issue by aliouchka** [leecade/react-native-swiper#202]
is it possible to swipe only with the arrows ?

**Comment by Moussawi7** [comment]
Yes,
by adding:
`scrollEnabled={false}`

**Comment by yazgazan** [comment]
@aliouchka did that solve your issue ?

**Comment by aliouchka** [comment]
Yes, Thank you :)
Le 2 août 2016 4:41 PM, "Guillaume de Sagazan" <notifications@github.com> a
écrit :
