### ISSUE TITLE
iOS swiper can't load Image after pop 

### ISSUE THREAD

**Issue by chevins** [leecade/react-native-swiper#206]
swiper has 3 image loading from url, and I set the autoplay prop, then I push to the next View(using navigator animated) , wait few seconds and pop back 。。And the image just go away ,it will show after next autoplayTimeout . I don't know how to fix it~~

**Comment by chuhanan** [comment]
I have the same problem, set autoplay time quickly ?

**Comment by DBshaoYan** [comment]
Swiper  add  removeClippedSubviews = {false}
