### ISSUE TITLE
Performance optimization concerning huge pages

### ISSUE THREAD

**Issue by PhilippKrone** [leecade/react-native-swiper#21]
Hello,

first of all: thanks a lot for this nice swiper! I'm currently using it for about 20 pages, each of the pages being quite big. Is there any way to optimize the rendering (e.g. render only some pages next to the currently active page), as the initial loading is taking about 3 seconds in my case at the moment.

Regards
Philipp

**Comment by skitterm** [comment]
I'm having a similar issue with large-ish image per page with 100 pages.

**Comment by mosch** [comment]
#35 is the same. i'm also having these problems.

**Comment by leecade** [comment]
duplicate track in #35
