### ISSUE TITLE
Is not support React Naitve 0.30 ?

### ISSUE THREAD

**Issue by zpp-gp** [leecade/react-native-swiper#214]
ask for  question:
Is not support React Naitve 0.30 ?

**Comment by yazgazan** [comment]
From personal experience, it supports at least all react-native versions from 0.25.1 to 0.31.0. So 0.30.x versions should work.

**Comment by AdamBrodzinski** [comment]
0.30 works for me.

**Comment by rknell** [comment]
Hey @zpp-gp 

Are you using the example? If so then yes it hasn't been updated to support react > 0.25

Change the import / require statements up the top from:

```
var Swiper = require('react-native-swiper')
// es6
// import Swiper from 'react-native-swiper'

var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
} = React;
```

 to:

```
import Swiper from 'react-native-swiper'
import React, {Component} from "react"
import {StyleSheet, Text, View} from "react-native"
```

**Comment by tasiyo7333** [comment]
I will update the example soon.
