### ISSUE TITLE
How to access the functions of children components of swiper?

### ISSUE THREAD

**Issue by josephan** [leecade/react-native-swiper#215]
The main issue is I am unable to access the `refs` of the `Swiper` component from the `_onMomentumScrollEnd` function.

How do I get access to the functions of the children components of Swiper?

`context.refs` returns a really long output in the console

but `context.refs.word0` returns undefined.

```
// libraries
import React, { Component } from 'react';
import { Dimensions, Text, View, StyleSheet } from 'react-native';
import Swiper from 'react-native-swiper';
import WordPage from './WordPage';

var { width, height } = Dimensions.get('window');

export default class TopicPage extends Component {
  _onMomentumScrollEnd(e, state, context) {
    console.log(context.refs.word0);
  }
  
  render() {
    return (
      <View style={styles.page}>
        <Swiper style={styles.wrapper} ref={'swiper'} loop={false} height={height - 72}
          onMomentumScrollEnd={this._onMomentumScrollEnd}>
          {this.props.sentences.map((item, key) => {
            return (
              <WordPage key={key} ref={'word' + key}
                word={item.word} />
            );
          })}
        </Swiper>
      </View>
    );
  }
}


const styles = StyleSheet.create({
  page: {
    marginTop: 72,
  },
  wrapper: {
  },
})
```

**Comment by getnashty** [comment]
Do you have any examples / docs of grabbing refs through context? String refs are going to be deprecated in favor of callback based refs, ie. `<WordPage key={key} ref={(wp) => {this[`_word${key}`] = wp;}} />` 

Then you access the ref through this._word0...

**Comment by josephan** [comment]
Hey getnashty I had no idea that was the case. Thank you so much for your help.
