### ISSUE TITLE
[help] Fixed index

### ISSUE THREAD

**Issue by flaviotobi** [leecade/react-native-swiper#218]
Hi, what i'm trying to do is to "fix" the index of the swiper.
i'm passing an  array with three position [0,1,2], and what i'm doing is change the information, when i swipe from right to left, i pass the information from [1] to position [0], [2] to position [1] and a i put new information in position [2] of the array.
In iOS i already did this, by changing  in the file react-native-swiper/src/index.js, but in android dosent work.
Anyone have an ideia ??

original file in line 193

    if (state.total === initState.total) {
      // retain the index
      initState.index = state.index
    } else {
      // reset the index
      initState.index = initState.total > 1 ? Math.min(props.index, initState.total - 1) : 0
    }

changed 

    if (state.total === initState.total) {
      initState.index =1
    } else {
      initState.index = 1
    }

**Comment by getnashty** [comment]
What happens in Android?

Also, you don't need the if conditional, if you're hardcoding initState.index = 1 in both cases.

**Comment by flaviotobi** [comment]
Hi there, tanks for the reply.
I know that i don't need the if conditional, it was for a better understanding where i change the code. :) 
In android if i swipe right to left  [1]->[2] the swiper index get stuck in index 2, it doesn't go back to position 1 when the information is updated.

If you prefer i can create a video/GIf showing what happens in android and in iOS

**Comment by flaviotobi** [comment]
**Update** From what i understand the problem is here.
I may be wrong, but from what i'm understanding the component ViewPagerAndroid as is own index.


    return _react2.default.createElement(
      _reactNative.ViewPagerAndroid,
      _extends({ ref: 'scrollView'
      }, this.props, {
        initialPage: this.props.loop ? this.state.index + 1 : this.state.index,
        onPageSelected: this.onScrollEnd,
        //onPageSelected: ()=>{},
        style: { flex: 1 } }),
      pages
    );

**Comment by flaviotobi** [comment]
Hi there, as i thought the ViewPagerAndroid  as its own index state, so when i hard coded the change of the index to 1 in swiper component, the index in ViewPagerAndroid didn't change, in swiper the index was 1, but in ViewPagerAndroid was 2 or 0.
Any way i forced using ViewPagerAndroid.setPageWithoutAnimation(1) to every time the data changes he goes to position 1.

Thanks for the reply @getnashty , and if anyone knows a better way of doing this please tell me :)
