### ISSUE TITLE
Set how many items I want to load with loadMinimal

### ISSUE THREAD

**Issue by facupedrazzini** [leecade/react-native-swiper#219]
Hi, Is there any way to use `loadMinimal` and instead of loading only 1 item (both sides), load a variable number of items?

**Comment by antoinerousseau** [comment]
why? when you swipe too fast?

**Comment by facupedrazzini** [comment]
remote images

**Comment by antoinerousseau** [comment]
I see, but you don't want to preload all. I guess you have a lot :)
