### ISSUE TITLE
Dynamic Items

### ISSUE THREAD

**Issue by brianantonelli** [leecade/react-native-swiper#22]
I'm loading remote data and then setup my views, but when I generate them dynamically it stacks them on a single screen. It looks like its grabbing the children in getInitialState() and they aren't available yet. When render() runs the children are there, but the total is set to 1.

**Comment by schouffy** [comment]
Although this is closed, the issue still exists. Is there a way around it ?

**Comment by CyrusZei** [comment]
this is so damn annoying. Is there any other modules instead of this ?
