### ISSUE TITLE
Is it possible to customize each dots ?

### ISSUE THREAD

**Issue by commit-master** [leecade/react-native-swiper#224]
Hey,

I was just wondering if it were possible to customize each activeDots and chose a specific color for each ?

Best regards,
Paul

**Comment by getnashty** [comment]
yes, you can use the `dot` and `activeDot` properties, please refer to the documentation

**Comment by commit-master** [comment]
I've been reading & reading the documentation, but I think I did not express my self well, sorry. Let's say I have 3 slides. I want dots to be a certain color, and active dot to be a different color for each slide. 
For example `activeDot(1) => blue;` `activeDot(2) => red;` `activeDot(3) => green;`

Sorry if I issue was unclear.

**Comment by mattnedrich** [comment]
Can this be re-opened to address the more specific question? Can you define page-specific dots?
