### ISSUE TITLE
scroll has a little problem

### ISSUE THREAD

**Issue by 362228416** [leecade/react-native-swiper#24]
I use swiper and inside embedded a ListView, when I first upwards sliding ListView, no problem, but before the end of the sliding effect no I loosen the fingers, sliding again, ListView can't slide, can only wait for it to stop, to continue to slide, not straight, I do not have this problem using a ListView alone, how to solve?

**Comment by olivierlesnicki** [comment]
Same issue here. With a normal ScrollView.

**Comment by leecade** [comment]
may the RN solve the problem, try it?

**Comment by olivierlesnicki** [comment]
@leecade RN 0.17 solved it

**Comment by leecade** [comment]
@olivierlesnicki thanks your good news
