### ISSUE TITLE
Examples not working in RN 0.33

### ISSUE THREAD

**Issue by tioback** [leecade/react-native-swiper#244]
Steps:

1. `git clone https://github.com/leecade/react-native-swiper.git`
2. `cd react-native-swiper/examples`
3. `npm install`
4. `react-native run-ios`

Result:

![simulator screen shot 22 de set de 2016 20 06 14](https://cloud.githubusercontent.com/assets/13951017/18769034/0befd386-8100-11e6-9b34-774cd2884f54.png)

Running React Native 0.33

**Comment by leecade** [comment]
thanks your test and follow your steps works here.

My ENV: `ios10` + `xcode8` + `macOS10.12`

```
react-native-cli: 1.0.0
react-native: 0.33.0
```

Any different?

**Comment by leecade** [comment]
I guess your `8081` server port ref to another project, make sure the port is free before run `react-native run-ios`

```bash
$ lsof -i tcp:8081
```
