### ISSUE TITLE
Prevent slider from going backwards on first page

### ISSUE THREAD

**Issue by ivansifrim** [leecade/react-native-swiper#251]
I have a full page slider with 3 pages.

When they are on page 1, I do not want tom to scroll backwards. 
When they are on page 3, I do not want them to scroll forward any more.

Can this be done with this swiper?

**Comment by getnashty** [comment]
Unless I'm misunderstanding the question, simply set the loop property to false on your Swiper component.

**Comment by fostertime** [comment]
@getnashty is right. just set loop={false} on the Swiper component.

**Comment by ivansifrim** [comment]
Great - thanks so much!

**Comment by leecade** [comment]
you got it

**Comment by Tom29** [comment]
@fostertime what if i want loop={true} but i want to prevent scroll backward and forward whenever i wanted? like it's the end of data list. I need it to make infinite scrolling, but it might be stop at first backward and latest page forward.

**Comment by fostertime** [comment]
@Tom29 you should be able to set that prop in state, and just swap out true/false depending on whatever state condition you have. so something like `loop={this.state.loopCondition}`
