### ISSUE TITLE
[question] Can this library be used for infinite list?

### ISSUE THREAD

**Issue by joonhocho** [leecade/react-native-swiper#253]
Forgive me for posting a question not an issue.

I want to use this library for an dynamic infinite list like Facebook Newsfeed that loads infinitely, but with fullscreen and swipe gestures.

Has anyone used it for such scenarios? Should it work as it?

**Comment by leecade** [comment]
yes. you just need maintain a queue.

`onTouchEnd`  fire load new feed make the queue +1

ref: https://github.com/leecade/react-native-swiper/blob/master/examples/components/LoadMinimal/index.js

**Comment by luongs3** [comment]
your solution is terrible @leecade
