### ISSUE TITLE
Loop doesn't work with images on Android.

### ISSUE THREAD

**Issue by machei** [leecade/react-native-swiper#265]
I will upload GIF:

![problem](https://cloud.githubusercontent.com/assets/7736131/19414662/60b940a8-9354-11e6-8556-a5d83a08dbce.gif)

I tried to initialize these images with other styles and props.

**UPDATE** Only last image isn't fine.

**Comment by machei** [comment]
I made misstake, i didn't refresh when images are loaded up.

**Comment by ammichael** [comment]
What do you mean by 'refresh'?

**Comment by machei** [comment]
Ignore that. Images were loaded more times than once , method shouldComponentUpdate wasn't setup.

After setup all images are displayed! Thanks for plugin.
