### ISSUE TITLE
[Compatibility] React Native 0.8.0-rc Error

### ISSUE THREAD

**Issue by MossP** [leecade/react-native-swiper#27]
Great plugin, thank you. Just a heads up - It no longer works in React Native 0.8.0-rc. The error is
```
dist/index.js

Requiring unknown module "react-timer-mixin".
```

**Comment by irfaan** [comment]
Also fails with same error on 0.7.1

**Comment by MossP** [comment]
I've now managed to get it working. I'm not sure which single element made it work but I did the following
 - created a new project `$ react-native init NewProjectName`
 - I reinstalled all my modules
 - ensured that there were no copies of `react-native` in any of the installed modules' "node_modules" folders.
 - Updated a plugin `RCTRefreshControl` https://github.com/Shuangzuan/RCTRefreshControl as it was causing the error logs to flag every other module but changing this removed many of those errors.

**Comment by ibrens** [comment]
So, I was having this issue and after I restarted xcode and the sim, it started working
