### ISSUE TITLE
please list react-native-timer-mixin as a dep

### ISSUE THREAD

**Issue by olivierlesnicki** [leecade/react-native-swiper#28]

**Comment by helveticafire** [comment]
Yes please!

**Comment by grabbou** [comment]
Or at least peer dependency.

**Comment by doei** [comment]
+1

**Comment by LeoYuan** [comment]
+10086

**Comment by kyle-ssg** [comment]
+1, first thing I noticed.

**Comment by RassaLibre** [comment]
+1

**Comment by kilgoremaskreplica** [comment]
+1

**Comment by grabbou** [comment]
We have forked this project month ago and are refactoring it to fit our internal projects, I should be able to release it soon. It actually works quite cool, there were just a few bugs that had to be fixed.

**Comment by navels** [comment]
> We have forked this project month ago and are refactoring it to fit our internal projects, I should be able to release it soon. It actually works quite cool, there were just a few bugs that had to be fixed.

Glad to hear this :)

**Comment by leecade** [comment]
fixed
