### ISSUE TITLE
scrollBy is not working

### ISSUE THREAD

**Issue by yuda1124** [leecade/react-native-swiper#282]
I want to control initial index. first , I try index property, but it is not work.
second, I try scrollBy function. My code is..

export default class detailView extends Component {

  constructor(props) {
    super(props);
  }

  componentDidMount(){
    console.log(this.props.rowID);
    this._swiper.scrollBy(this.props.rowID);
  }

  render() {
    return (
      <View>
        <Swiper style={styles.wrapper} showsButtons ref={(swiper) => {this._swiper = swiper;}} loop = {false}>
          {this.props.detailSource.map((value)=>{
            return (
              <View style={styles.slide}>
                <Image source = {{uri: value.url}}
                       style = {styles.image}/>
              </View>
            );
          })}
        </Swiper>
      </View>
    );
  }
}
but it is not work. i'm very confused...
plz help me..

**Comment by yuda1124** [comment]
Oh I solved. it is just my mistake.
sorry~~

**Comment by hadrienbbt** [comment]
Does your example work ?
On which object can I trigger the method scrollBy ?

I have an issue using this... 
Here is my ticket https://github.com/leecade/react-native-swiper/issues/339

**Comment by iamrutvik** [comment]
How you solved it?

Here is my snippet : 

```
<Swiper loop={true}
                  ref={(component) => { this.swiper = component; }}
                  showsPagination={false}>
            <View style={styles.slide}>
              <TrendingScreen/>
            </View>
            <View style={styles.slide}>
              <FavoritesScreen/>
            </View>
            <View style={styles.slide}>
              <HallOfFameScreen/>
            </View>
            <View style={styles.slide}>
              <SearchScreen/>
            </View>
</Swiper>
```

Then on button click : 

```
onPress = () => {
    this.swiper.scrollBy(3)
}
```

It's throwing `undefined is not an object(evaluating 'this.swiper.scrollBy')` error. What is the issue?

**Comment by jariwalabhavesh** [comment]
I am facing same issue as @iamrutvik  facing. it is work one time when we use scrollBy. on next it is showing undefined error

**Comment by jariwalabhavesh** [comment]
@iamrutvik  use this solution:

```
<Swiper loop={true}
                  ref="sliderX"
                  showsPagination={false}>
            <View style={styles.slide}>
              <TrendingScreen/>
            </View>
            <View style={styles.slide}>
              <FavoritesScreen/>
            </View>
            <View style={styles.slide}>
              <HallOfFameScreen/>
            </View>
            <View style={styles.slide}>
              <SearchScreen/>
            </View>
</Swiper>
```

```
onPress = () => {
    this.refs.sliderX.scrollBy(3)
}
```

in component constructor bind onPress method to access this context
```
constructor(props){
   super(props);
   this.onPress = this.onPress.bind(this); 
}
```

_**Note:**_ refs will only available once component render complete

**Comment by hadrienbbt** [comment]
Thank you it works perfectly

**Comment by jhon312020** [comment]
export default class App extends React.Component {
	constructor(props){
		super(props);
		this.onPressNext = this.onPressNext.bind(this);
	}
	onPressNext = () => {
		this.refs.swiper.scrollBy(1, true)
	}
	render() {
		return (
      <Swiper ref={'swiper'} style={styles.wrapper} loop={true} showsPagination={false} index={0}>
        <View>
          <Page1 />
          <Button
  					onPress={this.onPressNext}
  					title="Press Me"
					/>
        </View>
        
        <View >
          <Page2 />
        </View>
        
        <View>
          <Page3 />
        </View>
      </Swiper>
    )
	}
}

The above is snippet of code.  When I press button getting the error _this.refs.swiper.scrollBy is not a function.  Kindly let me know what is the mistake in my code.

**Comment by ducpt2** [comment]
@jhon312020  <Swiper ref={() => this.refSwifper = ref}.
onPressNext = () => {
		this.refSwifper.scrollBy(1, true)
	}

This will work.

**Comment by brunoda6** [comment]
My scrollBy only work once someone knows why?

**Comment by WickedBrat** [comment]
I'm using functional components, any directions on how to use refs here. It throws `swiper.scrollBy is not a function`

**Comment by bravemaster619** [comment]
> I'm using functional components, any directions on how to use refs here. It throws `swiper.scrollBy is not a function`

It's simple as this:

```javascript
export default function SwiperComponent() {
    const swiper = React.useRef(null);
    const handleNext = () => {
        if(swiper && swiper.current) {
           swiper.current.scrollBy(1);
        }
    }
   return (
       <Swiper
           ref={swiper}
       >
           <SafeAreaView>
               <Text>Sana</Text>
               <Button onPress={() => handleNext()} title="next" />
           </SafeAreaView>
           <SafeAreaView>
               <Text>Minatozaki</Text>
           </SafeAreaView>
       </Swiper>
   );
}
```
