### ISSUE TITLE
How to modify the dots' position?

### ISSUE THREAD

**Issue by wangdicoder** [leecade/react-native-swiper#289]
Like the title. When I set the height of the view, the position of dots doesn't meet my demand. So if I want to change the position of dots, how can I do it?

**Comment by wangdicoder** [comment]
Maybe I don't find the prop to modify the position, but I solve this problem.

I modify the native code directly....

`pagination_x: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent'
  },`

Just modify the "bottom" value, which will be OK~

**Comment by forrest23** [comment]
just use  <Swiper paginationStyle={{ bottom: 15 }} >  will be ok

**Comment by ababba15** [comment]
@forrest23 this is fine on iOS, but on Android dots hide when they are outside of Swiper container..

**Comment by davidpaulsson** [comment]
Confirm, this is not working on Android.

@ababba15 Did you find a solution for this?

**Comment by ababba15** [comment]
@davidpaulsson no, I didn't. Just created my own dots.

**Comment by leonel-lordford** [comment]
Can you provide an example of your own dots placed at the very bottom of the swiper component ?

**Comment by ababba15** [comment]
@leonel-lordford [here is the gist](https://gist.github.com/ababba15/bba8a168fa36fc9814cdbff20fe300e8)

It is very far from perfect code (sorry), but I hope you will be able to extract some useful parts.

**Comment by leonel-lordford** [comment]
I'll check it !!! Thx...

**Comment by cnabs** [comment]
Do you modify the source code or modify it in the style

**Comment by cnabs** [comment]
@movibe s

**Comment by ababba15** [comment]
Didn't touch the source code.

**Comment by kcbar** [comment]
This solution works on Android: https://github.com/leecade/react-native-swiper/issues/668#issuecomment-347995024

**Comment by kruupos** [comment]
For those who needs it on top `paginationStyle={{ position: "absolute", top: 0, bottom: undefined }}`

**Comment by SabarishChungath** [comment]
How can i place pagination dots under a text component ?

**Comment by FaisalKhawaj** [comment]
I want to align the dots position to my view in which there is skip and next button , but when i use  activeDotStyle:
    {

        backgroundColor: '#007aff', width: 5,
        height: 5, borderRadius: 4, marginLeft: 3,
        marginRight: 3,
        bottom: 90,
        marginBottom: 3,
    },
It is not responsive . Please someone help me
![dots](https://user-images.githubusercontent.com/56731703/109758257-1db8c700-7c0d-11eb-9168-227e6aba0967.JPG)

**Comment by Aryan6290** [comment]
For starters, use paginationStyle={{ bottom: -15 }}

**Comment by FrSenpai** [comment]
I know it's a bit late, but I tried to add paginationStyle={{ display:"flex" }} with 1.6.0 and now it's working (fit to swiper item block).
