### ISSUE TITLE
Woudl be nice to have a way to switch the current visible view programatically

### ISSUE THREAD

**Issue by manask88** [leecade/react-native-swiper#29]
It've been trying to test out modifying the index property using states, however, it doesnt seem to work. It would be great to be able to go to the left / right pages programmatically in addition to the current swipe left/ right funcionality

**Comment by olivierlesnicki** [comment]
This can already be done using the scrollTo(index) method.

**Comment by nautical** [comment]
Any example ?

**Comment by rreusser** [comment]
Can you clarify how one might use this? Does this require two-way binding? I.e. swiping modifies an index state variable, and modifying a state variable switches to a given slide? That would require extending this component with that behavior, right?

**Comment by nautical** [comment]
The way I am doing it in my project is assigning ref to it , you can do something like : 
 <Swiper style={styles.wrapper} ref={component => this._swiperobj = component} > ... </Swiper>

Then you can call this._swiperobj.scrollTo(1); or something like that based on your condition .

**Comment by rreusser** [comment]
Oh wow, I didn't know that was a thing you could do. I was doing it with two-way binding, e.g.:

```javascript
<Swiper
  index={this.state.swiperIndex}
  onIndexChange={(idx) => this.setState({swiperIndex: idx})}
> 
```

which of course requires implementing `onIndexChange` within Swiper, but I'm already digging through guts to solve a couple other corner cases…

**Comment by rreusser** [comment]
And also requires picking up the prop changes within Swiper. The ref method seems kind of like a hack, but it's pretty compelling when you just need to get the job done.

**Comment by nautical** [comment]
Yes , ref is a powerful tool , can be used in simple jobs .

**Comment by rreusser** [comment]
At any rate, I think I'll finish implementing the two-way method since it's more react-ish and should probably exist anyway. Commits will probably end up on this fork (if I can get the infinite loop case working): https://github.com/manandmoon/react-native-swiper

**Comment by rreusser** [comment]
@nautical revisiting this with some hindsight (and because it's now painfully unmaintained and doesn't work anymore). Yeah, you're totally right. That's way easier and perfectly reactish. Noob mistake. But looks like now we'll have to swap this out for [react-native-viewpager](https://github.com/race604/react-native-viewpager).

**Comment by olivierlesnicki** [comment]
@lecade is alive!!!

**Comment by leecade** [comment]
@olivierlesnicki yeah I work on RN again

**Comment by joaoeffting** [comment]
@nautical MY HERO <3
