### ISSUE TITLE
swiper width flex - 

### ISSUE THREAD

**Issue by patricktresp** [leecade/react-native-swiper#292]
Hej i do want to implement the swiper within a view, that has **not** full width.
Any way i am implementing the Swiper component it always has full width of the window.
I do not want to set fixed width / height - values for obvious reasons. 

So how do i implement the swiper so it only uses its available space within the parent container (which is within a flex-model ).
Can anyone help on that?

Thx!
Patrick

**Comment by matto1990** [comment]
I have the same issue with the height. I do not want to fix the value, but unless I do it will default to the height of the screen.

In my opinion, this is the incorrect behaviour and seems to go against what the documentation says. I think it should instead be set to `flex: 1` so it takes up the full space of the container it is in.

**Comment by patricktresp** [comment]
i now have to measure the containers the swiper is in and set width and height to fixed values, which is totally against flexbox model.

Hope this gets integrated sometime soon.

**Comment by patricktresp** [comment]
i now have to measure the containers the swiper is in and set width and height to fixed values, which is totally against flexbox model.

Hope this gets integrated sometime soon.

**Comment by afilp** [comment]
I have the same problem too.

**Comment by JulianKingman** [comment]
@patricktresp why is this closed?
