### ISSUE TITLE
Show numbers instead of dots?

### ISSUE THREAD

**Issue by aksonov** [leecade/react-native-swiper#3]
Great component! It would be good to have X/Y (X current page / Y total pages) customizable label string instead of dots for big lists.

**Comment by leecade** [comment]
thanks, Now the `dot` prop allow to custom element.

like:

```jsx
<View style={{backgroundColor:'rgba(0,0,0,.2)', width: 8, height: 8,borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 3,}} />
```

For custom label string with X/Y, my option is allow `dot` / `activeDot` props supports `function` type, like:

```
var renderDot = function(index, total) {
  return <View style={{}}><Text>{index}/{total}</Text></View>
}
<Swiper dot={renderDot}>
        <View style={styles.slide1}>
          <Text style={styles.text}>Hello Swiper</Text>
        </View>
      </Swiper>
```

And your opinion?

**Comment by aksonov** [comment]
Sounds great!

**Comment by leecade** [comment]
OK. CI later

**Comment by leecade** [comment]
Sorry so late @aksonov , Now there is a new prop `renderPagination` done.

see https://github.com/leecade/react-native-swiper/blob/master/examples/examples/swiper_number.js

Update doc later, thanks your idea.

**Comment by smithaitufe** [comment]
What is I need a custom pagination but also wants to render dots?

**Comment by Hari70a** [comment]
@leecade and @smithaitufe 
I also want both custom pagination and render dots. Is it possible?
