### ISSUE TITLE
animation,I need a squirm effect about indicator!

### ISSUE THREAD

**Issue by janryWang** [leecade/react-native-swiper#30]
Like this indicator's animation
![pbavb](https://cloud.githubusercontent.com/assets/4060976/8950447/51c93620-35f4-11e5-8ba6-0dbf2be557f6.gif)

**Comment by kfiroo** [comment]
+1
Would be nice to have.
Any idea how to approach this?

**Comment by olivierlesnicki** [comment]
The active indicator is just a component. You should be able to overwrite the component and add slight animation.

**Comment by leecade** [comment]
```jsx
this.state.width = 1
this.state.height = 1

<Swiper onScrollBeginDrag=(e) => {
  this.setState({
   width: 123
})
}
<Dot style={{width: this.state.width, height: this.state.height}}
```
