### ISSUE TITLE
Unable to resolve module Dimensions from 

### ISSUE THREAD

**Issue by PhilippKrone** [leecade/react-native-swiper#31]
Hello,

I get the following warning in the packager:
````javascript
Unable to resolve module Dimensions from .... dist.js
````

Any idea how to fix that? Everything is working correctly, just the message in the packager.

Regards

**Comment by helveticafire** [comment]
Upvote! :+1:

**Comment by cgarvis** [comment]
:+1:

**Comment by alejomendoza** [comment]
I still get this error with the current version, is someone updating the npm for this module?

**Comment by aksonov** [comment]
@leecade I'm getting this error as well...

**Comment by hufeng** [comment]
@leecade I'm getting this error as well

**Comment by lighthx** [comment]
I'm getting this error as well

**Comment by ghamaide** [comment]
Same, getting this error in .../dist/index.js

**Comment by viktors** [comment]
I'm experiencing the same issue. The full message is:

Unable to resolve module Dimensions from /Users/user/MyApp/node_modules/react-native-swiper/dist/index.js: Invalid directory /Users/node_modules/Dimensions

As far as I can tell the issue is that it's looking in wrong directory for Dimensions module (two levels above what it should be).

**Comment by antionio** [comment]
I'm getting this error too, similar to what @viktors described. Xcode can't build after adding this library and example code.

**Comment by hmm29** [comment]
same error, 
this needs to get fixed asap

**Comment by PhilippKrone** [comment]
Hi,

you can fix it by changing the following in dist/indexjs:

from:
````javascript
var _Dimensions = require('Dimensions');

var _Dimensions2 = _interopRequireDefault(_Dimensions);

var _Dimensions$get = _Dimensions2['default'].get('window');
````

to

````javascript
var React = require('react-native');
var {
  Dimensions
} = React;
var {width, height} = Dimensions.get('window');
````

**Comment by hmm29** [comment]
Thanks so much @PhilippKrone !

**Comment by FrankSalad** [comment]
Did that, now I'm getting `Can't find variable: _Dimensions$get`

**Comment by andresn** [comment]
https://github.com/leecade/react-native-swiper/pull/64

**Comment by leecade** [comment]
fixed
