### ISSUE TITLE
Issue with Focused Text inside Swiper

### ISSUE THREAD

**Issue by a-koka** [leecade/react-native-swiper#321]
Notice the example below where there is a `Text` field and a `TouchableHighlight` button. When pressing the button after typing some text, the focus doesn't shift to the button immediately and the button requires a second click to trigger its `onPress`. The same code works fine when used outside a `Swiper` so I thought this may be a `Swiper` issue.

I realize that this may be a challenging bug to fix.  Any workaround suggestions in the meanwhile would also be helpful.

```
<Swiper ref={s => this.swiper = s} loadMinimal={true} showsButtons={false} loop={false} height={200} showsPagination={false} scrollEnabled={false}>
  <View>
    <View>
      <TextInput
        ref='email'
        autoCapitalize='none'
        autoCorrect={false}
        placeholder='Email'
        underlineColorAndroid='transparent'
        placeholderTextColor='white'
        value={this.state.email}
        onChangeText={(email) => this.setState({email})}
        style={{flex: 1, margin: 10, padding: 5, height: 20}}
      />
    </View>
    <View style={{alignItems: 'center', marginTop: 40}}>
      <TouchableHighlight underlayColor="#EDA309" onPress={() => alert('Button Pressed')}>
        <Text>Next</Text>
      </TouchableHighlight>
    </View>
  </View>
</Swiper>
```

**Comment by a-koka** [comment]
This is partially addressed in `0.40` and being updated in `0.41`

**Reference**
https://github.com/facebook/react-native/commit/552c60192172f6ec503181c060c08bbc5cbcc5a4

**Comment by maxstudener** [comment]
This is still broken on iOS

**Comment by ppyurkin** [comment]
I encountered an issue in version 1.6.0 (specifically affecting Android) where the `onPress` function of a Button is not being called when there's focus inside a TextInput, which is placed within a Swiper component. From what I understand, the problem is related to the ScrollView. To resolve this, you can pass `keyboardShouldPersistTaps={"always"}` to the Swiper component, like so:

```js
<Swiper
    keyboardShouldPersistTaps={"always"}
    // other props
>
    {/* Swiper content */}
</Swiper>
```
This change should address the issue.
