### ISSUE TITLE
don't support Android ListView renderHeader 

### ISSUE THREAD

**Issue by kliuj** [leecade/react-native-swiper#322]
with Android ListView renderHeader , it will be a  blank page, It seems that  the  ViewPagerAndroid  don't support  Android ListView renderHeader

**Comment by chlee114hk** [comment]
try to add removeClippedSubviews to ListView component

**Comment by CarGuo** [comment]
set removeClippedSubviews（false） to ListView work for me!!!

**Comment by kliuj** [comment]
thanks
