### ISSUE TITLE
How to achieve infinite scroll/infinite swipe without sacrificing performance?

### ISSUE THREAD

**Issue by kenma9123** [leecade/react-native-swiper#331]
I'm making a swiper where there are a lot of views maybe hundreds or thousands. I'm not sure if this is a good idea.  But it would be great if we can make it like a list item. Where it loads the other views when reach a certain range. Just like an infinite scroll. Is that actually possible? I'm not sure how to explain it but I do hope you get the idea.

**Comment by kenma9123** [comment]
I think I found my answer `loadMinimal` saves the day. Thanks

**Comment by gezichenshan** [comment]
The loadMinimal makes no sense to mine.
