### ISSUE TITLE
Dynamic Swiper Index Prop Fails on Android

### ISSUE THREAD

**Issue by evancloutier** [leecade/react-native-swiper#337]
Currently trying to render an initial swiper page using the following code:

```javascript
render() {
    const deviceWidth = Dimensions.get('window').width
    const deviceHeight = Dimensions.get('window').height

    return (
      <Swiper showsButtons loop = { false } index = { this.state.key }>
        { this.state.items.map((item) => {
          return (
            <View key = { item.id }>
              <Image
                style = {{ width: deviceWidth, height: deviceHeight }}
                resizeMode = 'contain'
                source = {{ uri: item.photo.image_url }}
              />
            </View>
          )
        })}
      </Swiper>
    )
  }
```

Where `this.state.key` is the index of a photo when pressed on a grid (going from grid -> full screen, hence why I want this image to be rendered first).

The following code works as it should on iOS, but I'm not having any luck on Android. If someone wants to point me in the right direction, I can look into submitting a PR.

**Comment by cj4luv** [comment]
I try to solve this problem....

**Comment by JulianKingman** [comment]
Try passing it as a prop from the parent container. My guess is that the index is not being set fast enough (ie before the component renders).

**Comment by evancloutier** [comment]
@JulianKingman I ended up figuring this out, and I think you're right for the most part. I can't exactly recall, but I moved my state assignments into the `constructor` and `componentWillMount` methods, which seemed to fixed it. The problem wasn't with the `Swiper` component itself, but rather with a parent container.

I'm going to close this issue for now, but if anyone is having any problems feel free to open it up again and I'll be happy to help.

**Comment by pgonzalez-santiago** [comment]
Hey @evancloutier, I'm having the same issue as you. Could you please explain me better how you solved it?

**Comment by evancloutier** [comment]
@pgonzalez-santiago Can you paste some code or a gist? I'll try to help from there.

**Comment by pgonzalez-santiago** [comment]
@evancloutier of course.

I render this: 

          <Swiper ... index={this.state.clickedThumbnail}>
            {this.props.post.gallery.map((item, j) => {
              return (
                <OfflineImage
                  key={j}
                  ...
                 />
              )
            })}
          </Swiper>
        </View>

I set the state `this.state.clickedThumbnail` for the index when  a thumbnail is clicked.

The initital state is: 
` super(props) {
    this.state = {
      clickedThumbnail: 0
    }
  }` 

Its working perfectly on iOs but not in android even if I force the index to be for example 2.

**Comment by evancloutier** [comment]
@pgonzalez-santiago try adding a `componentDidMount()` method to your component. I had my`render()`, `componentDidMount()` and `constructor` set up like this:

```javascript
constructor(props) {
    super(props)

    // Initializing the state attributes to be the appropriate data types
    this.state = {
      page: '',
      key: '',
      items: [],
    }
  }

  componentWillMount() {
    const items = this._transformPhotoArray(this.props.navigation.state.params.array)

    // Note that I'm updating the state here
    this.setState({
      page: this.props.navigation.state.params.page,
      key: this.props.navigation.state.params.key,
      items: items
    })
  }

  render() {
    const navigationParams = this.props.navigation.state.params

    return (
      <View style = { styles.container }>
        <View style = { styles.swiperContainer }>
          <Swiper
            loop = { false }
            height = { height }
            index = { this.state.page == 1 ? this.state.key : (this.state.key) + ((this.state.page - 1) * 20) }
            onMomentumScrollEnd = { this._onMomentumScrollEnd.bind(this) }
            renderPagination = { this._renderPagination.bind(this) }
            renderNewItems = { this._renderNewItems.bind(this) }
            fetchNextPage = { this._fetchNextPage.bind(this) }>
            { this.state.items.map((item, key) => {
              return (
                <View key = { key } style = { styles.imageContainer }>
                  <Image resizeMode = 'contain' style = { styles.image } source = {{ uri: item.photo.image_url }}/>
                </View>
              )
            })}
          </Swiper>
        </View>
        <PhotoFooter
          avatar = { navigationParams.avatar }
          photographer = { navigationParams.photographer }
          created = { navigationParams.created }
          views = { navigationParams.views }
          votes = { navigationParams.votes }
          >
        </PhotoFooter>
      </View>

    )
  }
```

I believe the issue is that the `index` prop of the `Swiper` isn't being updated fast enough when it comes to the Android platform, and is defaulting to a value of zero.

Note that I have a bit more going on here in my `render()` than you probably need - I was adding a custom footer component to the bottom of the swiper. 

Hope this helps.

**Comment by renay007** [comment]
Thank you very much!!! 💯  👍 🥇

**Comment by ettaibi** [comment]
any one resolved this on android ? still having the same issue

**Comment by bmxklYzj** [comment]
still has this problem. set index on Swiper's prop, it's ok on iOS, but not take effect on Android.
