### ISSUE TITLE
Overflowing controls with many swiper items, ideas?

### ISSUE THREAD

**Issue by JulianKingman** [leecade/react-native-swiper#342]
Any ideas or best practices for what to do with control buttons when you have more than fit on the screen? Example below:
![screen shot 2017-02-10 at 1 49 06 pm](https://cloud.githubusercontent.com/assets/1566400/22839532/d2a6ca06-ef97-11e6-8825-980b2820cdf4.png)

**Comment by JulianKingman** [comment]
I did this: 
````javascript
<Swiper
      index={taskIndex}
      loadMinimal
      loadMinimalLoader={<Loading />}
      renderPagination={(index, total, context) => {
        if (total < 20) return context.renderPagination();
        return <View style={style.pagination}><Text>{`${index} / ${total}`}</Text></View>
      }}
    >
````

**Comment by chapeljuice** [comment]
You might want to think about changing the design and utilizing numbered pagination instead of all those dots. Just a suggestion!

**Comment by Mamdouh-Symbyo** [comment]
You can check if swiper greater than X make dot small.
`
dot: {
    height: 4,
    width: 4,
    marginLeft:2,
    marginRight:2,
  },
`

`<Swiper
        style={styles.mainContainer}
        index={0}
        loop={false}
        dotStyle={[styles.dot, styles.dotOpacity]}
        activeDotStyle={[styles.dot, styles.activeDot]}
        bounces
      >`
