### ISSUE TITLE
it dosen't work when in a listview

### ISSUE THREAD

**Issue by sessionbean** [leecade/react-native-swiper#345]
When a swiper was put in a listview like this:

renderRow(row, sectionID, rowID, highlightRow){

        if(rowID==0){
            return (
            <Swiper height={32} style={{zi:9}}
                    loop={true}
                    index={0}
                    autoplay={true}>
                <Image
                    style={{flex:1}}
                    source={{uri:imagesArr[i].image_url}}
                    />
            </Swiper>
            )
        }
.....
}

it shows nothing but blank, and some dot.
What should I do to make this work?

**Comment by nhducit** [comment]
You should set width and height for images
