### ISSUE TITLE
Memory Leak with 100-page slider (and images)

### ISSUE THREAD

**Issue by skitterm** [leecade/react-native-swiper#35]
I have a slider that swipes through about 100 1/2-page images. It looks great, and works great on the simuator. However, when I run it live it runs for a few seconds, and then crashes with the below error in XCode:

Terminated due to memory error
And in the Output on XCode: Received memory warning.

On my end, I'm building out the jsx dynamically (I loop over my list of items and make jsx for each using items.map).

I'm not sure why it's causing it to crash. Has anyone else seen this?

**Comment by mosch** [comment]
I'm looking forward to use the slider in a project with a similar use-case. I'll have several sliders with up to 100 elements. 
We may look out for a point to optimise performance.

**Comment by leecade** [comment]
which version Xcode / RN used

or show me some code thanks, I will follow it

**Comment by getnashty** [comment]
@skitterm @mosch I'm closing this issue for now, if either of you test out the swiper with the loadMinimal property and don't have success we can re-open
