### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by 74io** [leecade/react-native-swiper#36]
Great module! Any pointers on how to get it working when changing the device orientation to landscape?

**Comment by rt2zz** [comment]
+1 afaik it does not support landscape?

**Comment by jasonmerino** [comment]
Looks related to #16

**Comment by esutton** [comment]
Any suggestions for making react-native-swiper work in landscape mode?

Thanks for a great component!

**Comment by GuillaumeMunsch** [comment]
Any news on this ?

**Comment by uriklar** [comment]
+1

**Comment by dgurns** [comment]
+1 too

**Comment by ciriac** [comment]
+1

**Comment by RiusmaX** [comment]
+1 too. I've tried so many ways to force the update after device rotation, like invert width and height, but it's not a good practice at all. 

Someone did find a decent solution ?

**Comment by timmywil** [comment]
The problem is that Swiper gets windows dimensions one time on execute rather than on render, but I've worked around this by getting window dimensions in my render function and passing those values to the `width` and `height` props of `<Swiper>`.

```jsx
render () {
  const { width, height } = Dimensions.get('window')
  return (
    <Swiper width={width} height={height}>
       ...
    </Swiper>
  )
}
```

When the window dimensions change, Swiper's `componentWillReceiveProps` method is called, which updates the dimensions in its state.

**Comment by dantman** [comment]
@timmywil Yup

Though ultimately I don't think Swiper even has a reason to try using the window dimensions to fill the page. It makes much more sense to use `flex` and `onLayout`.

**Comment by timmywil** [comment]
Seems this broke again when I updated react-native to 0.46.2. `componentWillReceiveProps` isn't called anymore. This project doesn't seem to be getting support anymore, so I may fork it or just build a custom one for my needs.

**Comment by SSTPIERRE2** [comment]
Does this properly change orientation to landscape now? I've been unable to get that working so far.

**Comment by anand-neema** [comment]
Is it working now ?
