### ISSUE TITLE
Is it possible to modify the transition time while its changing the content of the swiper in autoplay?

### ISSUE THREAD

**Issue by gianpieroc** [leecade/react-native-swiper#364]
I'm trying to slow down the time between contents inside the swiper, but I've not found a way yet. Is it possible? Thanks :smile:

**Comment by Bahri08** [comment]
Have you found any solution please?

**Comment by gianpieroc** [comment]
The library uses the method scrollTo({ x, y, animated }) from React Native ScrollView Component. So the animation depends on that.

look at these links:

https://stackoverflow.com/questions/36035648/how-to-alter-scrollview-scrollto-scrolling-speed
https://react-native.canny.io/feature-requests/p/add-speed-attribute-to-scrollto

This issue is not possible to fix with the current implementation.

**Comment by Bahri08** [comment]
Thank you.

Le 27 juin 2017 14:54, "Gianpiero Costanza" <notifications@github.com> a
écrit :

**Comment by chenyi5266** [comment]
you can close autoplay   , use scrollBy to play by hand 
<Swiper  ref="sw" >...</Swiper>

setInterval() => {  
    this.refs["sw"].scrollBy(1); // 0,1,2,3    loop
    ...
},3000)

just like this ..

**Comment by ShridharCodewave** [comment]
Any solution?
