### ISSUE TITLE
Syncing scroll index between multiple nested swipers

### ISSUE THREAD

**Issue by bkotos** [leecade/react-native-swiper#373]
Hello,

I have one vertical swiper with multiple nested horizontal swipers.  I am trying to keep the nested horizontal swipers in sync.  I.E. if I swipe to index 2, all the other nested swipers should also change to index 2.  The nested swipers will always have an equal number of panes.

To accomplish this, I created a `scroll()` method that loops through each swiper and calls `.scrollBy()`. ([here](https://gist.github.com/bkotos/a0fee87716710f10fb414201a6de883e#file-index-ios-js-L74:file-index-ios-js-L78))

Invoking `.scrollBy()` (using my method) on the swipers works for the first call ([here](https://gist.github.com/bkotos/a0fee87716710f10fb414201a6de883e#file-index-ios-js-L49:file-index-ios-js-L53)).  However, any subsequent calls don't update the swipers to the correct index ([here](https://gist.github.com/bkotos/a0fee87716710f10fb414201a6de883e#file-index-ios-js-L55:file-index-ios-js-L60)).

Also, I tried hooking my method into the `onMomentumScrollEnd()` callback ([here](https://gist.github.com/bkotos/a0fee87716710f10fb414201a6de883e#file-index-ios-js-L68:file-index-ios-js-L72)).  This caused a huge event loop which has been problematic.  However, for now I'm just trying to get to the bottom of my issues with `.scrollBy()`.

Am I doing something wrong?  How can I keep the scroll index of multiple swipers in sync?  Any help would be much appreciated.

**Code:**
https://gist.github.com/bkotos/a0fee87716710f10fb414201a6de883e

**JSX hierarchy:**
* Swiper (vertical)
  * View
    * Swiper (horizontal)
      * View
      * View
      * View
  * View
    * Swiper (horizontal)
      * View
      * View
      * View
  * View
    * Swiper (horizontal)
      * View
      * View
      * View

**UI:**
<img width="376" alt="screen shot 2017-03-27 at 11 52 53 pm" src="https://cloud.githubusercontent.com/assets/6282681/24388429/961fface-1348-11e7-9be0-a8a3c8028534.png">

**Comment by hanford** [comment]
@bkotos any luck? Trying to achieve the exact same thing.

**Comment by bkotos** [comment]
@hanford no luck so far 🙁, but glad to see I'm not the only one having this issue.  This is important for a project I'm working on, so I just put a bug bounty on this issue: https://www.bountysource.com/issues/43520768-syncing-scroll-index-between-multiple-nested-swipers

**Comment by hanford** [comment]
@bkotos I forked the library and hacked on this a little bit. I made a fork that works for me, though my implementation is a little different than yours. 

Here is the commit that made it work for me: https://github.com/hanford/react-native-swiper/commit/88a0b054106eeb7d422f326ff8932f3422179715 ... basically, whenever `componentWillReceiveProps` gets called, I force the other `swipers` to update to it. It's pretty buggy if you scroll fast enough tho :/ .. so it's a more of a temporary solution than a fix.

Then in my parent state, I have an `x, y` that get updated on the according `onMomentumScrollEnd` .. passing the stored state into each swiper. 

It is buggy if you scroll before the `componentWillReceiveProps` though.

**Comment by hanford** [comment]
@bkotos, fixed most of the bugs I was facing last night and pushed version `1.6.0` .. it might work for you, but obviously can't guarantee any support.

**Comment by ryanwhiley** [comment]
@hanford do you have any examples of this working? I updated my src/index file to what you have [here](https://github.com/hanford/react-native-swiper/blob/master/src/index.js) but I'm still not able  get it to work properly.  I also used the index.ios.js code that bkotos linked in the original post. Any help would be awesome, thanks!
