### ISSUE TITLE
New Feature Pull to refresh 

### ISSUE THREAD

**Issue by roman2710** [leecade/react-native-swiper#391]
Pull to Refresh already exists for ListView and ScrollView as react native's refresh control. Support will be much appreciated.

**Comment by ohsik** [comment]
+1

**Comment by qwlong** [comment]
@roman2710 did you solve refresh problem ?

**Comment by roman2710** [comment]
Solved by wrapping the swiper within a scroll view

**Comment by qwlong** [comment]
OK, Let me try it

**Comment by anonfreak** [comment]
The "fix" by @ghost isn't working anymore... I get a "exception thrown while executing ui block" when i wrap the Swiper-component within a ScrollView
