### ISSUE TITLE
scrollTo() breaks after attempting to swipe to cell before first

### ISSUE THREAD

**Issue by MossP** [leecade/react-native-swiper#41]
Title says it all really. If I have a swiper that has 4 slides and on the first slide I have button that call `scrollTo(index)` they all work but it I then swipe back to the start and try to swipe one extra slide before the start then `scrollTo(index)` stops working. Manually swiping to the second slide and back again corrects the issue.

**Comment by leecade** [comment]
please show me the code, I will check it & fix

**Comment by rajkissu** [comment]
Merged #87
