### ISSUE TITLE
Is it possible to disable swiping behavior

### ISSUE THREAD

**Issue by olivierlesnicki** [leecade/react-native-swiper#42]

**Comment by irfaan** [comment]
+1

**Comment by leecade** [comment]
```jsx
scrollEnabled={false}
```

ref: http://facebook.github.io/react-native/docs/scrollview.html#props

**Comment by igorshmukler** [comment]
this disables scrolling of the scrollview, right? what about swiping, for slides?

**Comment by wootwoot1234** [comment]
Worked for me.

@leecade this isn't in the docs.  Can you add it?  I'm sure other people are looking for it too.

**Comment by irfaan** [comment]
@wootwoot1234 the beautiful nature of github is that it is collaborative - you can add it to the docs yourself! :dancer:

**Comment by wootwoot1234** [comment]
@irfaan Why don't you take your own advice?  You had the same problem I had.

**Comment by irfaan** [comment]
@wootwoot1234 Your passive aggressiveness aside, sure - I don't mind! :+1:

**Comment by leecade** [comment]
PR is welcome 💯
