### ISSUE TITLE
react-native-swiper with array

### ISSUE THREAD

**Issue by aditiadananjaya** [leecade/react-native-swiper#420]
i have array with image. how can i use react-native-swiper with array and i need to display the image
can someone give me a example

**Comment by gigeos** [comment]
@aditiadananjaya You can do something like this:

```
const pages = [...new Array(pagesCount + 1)].map((it, idx) => {
       return this.renderPage(idx);
});

<Swiper
     height={this.state.height}
    width={this.state.width}
 >
   {pages}
</Swiper>
```

**Comment by aditiadananjaya** [comment]
its work sir thank you so much

On Mon, May 22, 2017 at 9:55 PM, Geoffrey SAUTREAU <notifications@github.com
