### ISSUE TITLE
Initial index not working?

### ISSUE THREAD

**Issue by BerndWessels** [leecade/react-native-swiper#43]
Hi
I cannot set the initial index. It always shows the first page. What is wrong?

Thank you
Bernd

In this example I expect the page at index 3 to be the visible at startup, but it is not :(

        render() {
            return (
                <Swiper showsButtons={false} index={3}>
                    {this.props.route.approvalIds.map(function (approvalId, pageIndex) {
                        return (
                            <View style={{flex: 1}} key={pageIndex}>
                                <Approval approvalId={approvalId} pageIndex={pageIndex} pageCount={this.props.route.approvalIds.length} />
                            </View>
                        );
                    }.bind(this))}
                </Swiper>
            );
        }

**Comment by exentrich** [comment]
Same problem!

**Comment by dhrrgn** [comment]
@BerndWessels @exentrich Work around (probably better anyways TBH): 

1. Add a ref to your Swiper component (e.g. `ref="swiper"`)
2. In your `componentDidMount` do call `scrollTo`: `this.refs.swiper.scrollTo(this.props.initialIndex);`

**Comment by BerndWessels** [comment]
Thank you @dhrrgn .

Will try it today.

Would be great to have a workaround but would still love seeing it fixed.

Cheers
Bernd

**Comment by dhrrgn** [comment]
@BerndWessels @exentrich Just figured out that this is actually fixed...it was just never published to npm.  You can just install from the repo to fix the issue.

**Comment by BerndWessels** [comment]
@dhrrgn Oh, great news. Would be good if you guys could publish it to npm.

**Comment by leecade** [comment]
sorry for publish so later, but there is a new version
