### ISSUE TITLE
Can I get current index when the user swiped?

### ISSUE THREAD

**Issue by brendan-rius** [leecade/react-native-swiper#436]
I want keep the state of my slider synced in Redux, therefore I need to know when the user swiped.

Is that possible?

**Comment by adnbsr** [comment]
We can get swiper's `nextState` via `componentWillUpdate`

```
Swiper.prototype.componentWillUpdate = (nextProps, nextState) => {
    console.log(nextState.index)
}
```

**Comment by brendan-rius** [comment]
Fixed in #437 

Someone willing to merge?

**Comment by adnbsr** [comment]
It seems that the owner of this repo has stopped to contribute.

**Comment by zachrnolan** [comment]
Would love this feature, @leecade any way you can merge this to master?
