### ISSUE TITLE
null in swiper will still be rendered

### ISSUE THREAD

**Issue by Dogzhou** [leecade/react-native-swiper#438]
there is a logic inside swiper tag, which is show a banner when it's a certain time. like this: (at_certain_date is a function return true or false)
```
<Swiper
    showsButtons={false}
    autoplay
    height={178}
    autoplayTimeout={5}
    removeClippedSubviews={false}
>
    <TouchableOpacity key="1">
        <Image source={require('./resources/a.png')} >
            { 'a' }
        </Image>
    </TouchableOpacity>
    {at_certain_date && (<TouchableOpacity key="2">
         <Image source={require('./resources/b.png')} >
             { 'b' }
         </Image>
    </TouchableOpacity>)}
</Swiper>
```
there will be a white block in swiper even at_certain_date is `false`, then I tried to insert a {null} into `swiper` tag, same behaviour, I wonder what's the best solution under this case.

**Comment by ChristianTucker** [comment]
Create an array of elements to render, then apply them to the Swiper.

**Comment by Dogzhou** [comment]
thanks man, sounds like a plan, we used to consider this solution, then give it up, as element structure is kind of complex, anyway, it's still our best choice
