### ISSUE TITLE
Arial font not available in Android simulator

### ISSUE THREAD

**Issue by JavRok** [leecade/react-native-swiper#444]
Hi, the swiper is working perfectly in ios, but I'm getting an error in Android simulator (Nexus 5 on Android Studio), that says Arial is not a system font. 
The line triggering this issue is 86 on src/index.js. 
I'm using [create react native app](https://github.com/react-community/create-react-native-app), which uses Expo on the background. 

![image](https://user-images.githubusercontent.com/1526972/27426716-d968da16-573c-11e7-8569-c1c6a0c08cd2.png)

Thanks

**Comment by aglio** [comment]
I had the same problem, but I solved by adding Arial font to my app.  
1. Download Arial font.
https://jp.ffonts.net/Arial.font.download
2. Add "Arial.ttf" to some directory of your project.
3. Loading the font in your app by "Expo.Font" API.

e.g.
```
import { Font } from 'expo';
export default class App extends React.Component {
  state = {
    fontLoaded: false
  }
  async componentDidMount() {
    await Font.loadAsync({
      'Arial': require('./path/to/fonts/Arial.ttf')
    });
    this.setState({ fontLoaded: true });
  }
  render() {
    if (!this.state.fontLoaded) return null;
    return (
      <Main /> 
    );
  }
  // ...
}
```

**Comment by charlesdeb** [comment]
I have the same issue, and - as a workaround - have added ```arial.ttf``` to my project. However,

a) I am using other fonts in my app.
b) Arial requires an extra 358k of download to my users which I'd prefer to save them...

I am new to react-native. Can I override this default behaviour by specifying a fontFamily in the component somewhere? Just looking through the code, it doesn't look like I can do that, but I am not sure.

**Comment by jbakerdev** [comment]
If you are already using a custom font you can just add a duplicate require with 'Arial' as the key. Silly but no bloat at least...:)

**Comment by zachdixon** [comment]
Looks like it's being required for the control buttons (next/previous arrow buttons) so you can bypass this by either not showing the controls or providing your own `nextButton` and `prevButton` props:

```
<Swiper nextButton={<Text>&gt;</Text>} prevButton={<Text>&lt;</Text>} />
```
