### ISSUE TITLE
Display parts of previous and next slides/pages

### ISSUE THREAD

**Issue by andreaslindahl** [leecade/react-native-swiper#45]
Is it possible to use this component to display parts of the previous and next slides in the carousel, without changing the source? I.e. have the current page in the center and show a couple of pixels of the previous slide to the left and couple of pixels of the next slide to the right?

**Comment by sslash** [comment]
Why was this issue closed? I would love to be able to do the same

**Comment by sotocodes** [comment]
I want to be able to do this too... Do you @sslash @andreaslindahl have some ideas?

**Comment by bd-arc** [comment]
Hi guys! We were having a similar need and ended up creating our own plugin for that: https://github.com/archriss/react-native-snap-carousel

Hope that could help!

![react-native-snap-carousel archriss aix](http://i.imgur.com/UFsPlz2.gif)
![react-native-snap-carousel](http://i.imgur.com/sK5DKaG.gif)
