### ISSUE TITLE
点击翻页

### ISSUE THREAD

**Issue by gitfdy** [leecade/react-native-swiper#451]
有没有一个状态可以控制翻页呢 我想点击修改这个状态 然后进行跳转到指定页面

**Comment by gitfdy** [comment]
找到方法了

**Comment by zengyimou** [comment]
什么方法 大哥

**Comment by mrdezzods** [comment]
Guys let me know once the issue is solved. Then I can close it. 
@gitfdy @zengyimou

**Comment by 104gogo** [comment]
我也想知道啊！@gitfdy

**Comment by 104gogo** [comment]
scrollBy @zengyimou
