### ISSUE TITLE
Showing multiple slides in the same screen

### ISSUE THREAD

**Issue by stochris** [leecade/react-native-swiper#452]
Is there any way to have multiple slides "active" in the same screen ?

My approach was to have the slider have 500 width and the views holding each slide have 300 ( for example ), but looking the source, I see that the widths of the swiper and the children must be the same.

Is the any workaround for this ?

**Comment by yeelone** [comment]
i have the same problem

**Comment by stochris** [comment]
I used a manually build solution using a horizontal ScrollView. If you don't need any extra stuff beside the scroll, it might work for you
