### ISSUE TITLE
Swiper does not render on Android

### ISSUE THREAD

**Issue by petivagyok16** [leecade/react-native-swiper#453]
As i mentioned in the title, swiper does not appear on Android. It works fine in iOS simulator btw.
No build errors.
Any ideas?

**Comment by Tzinov15** [comment]
See [446](https://github.com/leecade/react-native-swiper/issues/446) I think it's the same issue

**Comment by petivagyok16** [comment]
It turned out that my issue caused by embedding too much swiper inside eachother
