### ISSUE TITLE
Doesn't fit inside container unless width/height are hard-coded

### ISSUE THREAD

**Issue by rreusser** [leecade/react-native-swiper#47]
I'd like the Swiper to take up the full size of its parent `View` element. Approaches:

1. If I don't specify `width` and `height` attributes, the `Swiper` element extends outside the parent container to full-screen (gets size from device properties?).
2. Styling the container doesn't appear to have any effect.
3. If I hard-code `width` and `height` attributes it will sit inside the container, but I don't want to hard-code these numbers.

If the container is indeed `flex:1`, I'd expect it to expand to the parent container size rather than the full screen dimensions. Is there a way to achieve this?

**Comment by SDLyu** [comment]
I'm facing same issue

**Comment by rreusser** [comment]
Okay, so this is horrendously ugly on multiple fronts, but depending on how many times you need to do this… This does work for me… I'm basically just measuring the parent container after it renders ([plus a timeout](https://github.com/facebook/react-native/issues/953#issuecomment-95687732)), then just hard-coding it anyway. It's really not great. Forgive the ES6/7 notation, but it should be reasonably straightforward. Let me know if not. Or if you have a better solution.

```javascript
export default class ItemSwiper extends React.Component {

  constructor(props) {
    super(props)
    this.state = { width: null, height: null }
  }
  
  componentDidMount() {
    setTimeout(this.measureSwiper)
  }

  storeSwiperLayout = (ox, oy, width, height, px, py) => this.setState({ width: width, height: height })

  measureSwiper = () => this.refs.sillyWrapper.measure(this.storeSwiperLayout);

  renderSwiper = () => {
    if( this.state.width > 0 ) { 
      return (
        <Swiper style={styles.swiper} width={this.state.width} height={this.state.height}>
          { this.props.items.map(i => this.renderItem(i)) }
        </Swiper>
      )   
    }   
  }

  render() {
    return (
      <View style={styles.sillyWrapper} ref="sillyWrapper">
        { this.renderSwiper() }
      </View>
    )   
  }
}
```

**Comment by rreusser** [comment]
Also had to add:

```javascript
  componentWillReceiveProps(props) {
    if( props.width ) this.setState({ width: props.width || width })
    if( props.height ) this.setState({ height: props.height || height })
  },  
```

to the swiper module so that changes have an effect. Could just extend Swiper to add these.

**Comment by nickmaxwell10** [comment]
I just changed the container style position: 'relative' to flex: 1 in index.js and Voila!

**Comment by rreusser** [comment]
@nickmaxwell10 Haha, that's wayyyyy simpler! Oof. A month into RN now and some things that were so difficult have become so easy…

**Comment by leecade** [comment]
@rreusser yeah `flex:1` works fine, RN have a flex-like layout system easy to fit container

**Comment by CreativeManix** [comment]
I have the same issue, Could you please post a where flex:1 has to be set..?

**Comment by mrpatiwi** [comment]
Same problem here

**Comment by rafaelcorreiapoli** [comment]
Any workarounds on this ?

**Comment by rreusser** [comment]
@rafaelcorreiapoli Haven't looked at this in a long time so not sure exactly if/what the flex/positioning fix is, but honestly my approach was to rewrite the part I needed, which was really just the page indicator: https://github.com/rreusser/react-native-paged-scroll-view It's definitely not perfect, but that was my workaround.

**Comment by rafaelcorreiapoli** [comment]
@rreusser  Nice! thanks, I will try it out

**Comment by rreusser** [comment]
@rafaelcorreiapoli Disclaimer: @leecade's swiper actually works very well, but the flex issue and adding/removing items dynamically and styling things differently meant it was more straightforward to implemented the restricted subset of functionality. Suggesting mine as just another alternative depending on your needs, but not to take away from this repo. 😄  Also, it seems like I might have a small race condition going on, so I can't guarantee my approach is 100% perfect, but it worked great in production for us. Not working with RN much at the moment, but don't hesitate to let me know if you have issues with it. Good luck!

**Comment by kbrk** [comment]
Hi,
There is another approach.
In the index.js I add onLayout event for the component View and then I can set state width and height.



```
setSize(){
    const w = Dimensions.get('window').width
    const h = Dimensions.get('window').height
    this.setState({width:w, height:h})
}
render() {
..
return(
<View style={[styles.container, {
        width: state.width,
        height: state.height
      }]}
        onLayout={this.setSize.bind(this)}
      >
..
)
```
This works for me :)

**Comment by joehui** [comment]
Similar to kbrk's approach, I use the following workaround.

In my code that uses the Swiper, I have the following.  Seems to work perfectly for me.

```javascript
	constructor(props){
		super(props);
		this.state = {
			width: 0,
			height: 0
		};
	} 

	setSize(event){
		const w = event.nativeEvent.layout.width;
		const h = event.nativeEvent.layout.height;
		this.setState({width:w, height:h});
	}

	render() {
		return (
			<View style={{flex:1}}>
				<View style={{flex:0}}>
					... Some content on the header
				</View>
				<View style={{flex:1}} onLayout={this.setSize.bind(this)}>
					<Swiper
						height={this.state.height}
						width={this.state.width}
						...
					>
						... Some content
					</Swiper>
				</View>
			</View>
		);
	}
```

**Comment by narup** [comment]
@joehui - Your solution worked for me. Thanks
