### ISSUE TITLE
Is this package still being maintained  

### ISSUE THREAD

**Issue by AlmogRnD** [leecade/react-native-swiper#487]
I was wondering if this package is still being maintained and supported I see over 200 issues most of them questions and no answers?

**Comment by kshvmdn** [comment]
200+ issues, almost 40 PRs, no commit in ~8 months... 🙁

**Comment by arribbar** [comment]
We could work on a fork, no ?

**Comment by mrdezzods** [comment]
Hey guys,
I got answer from @leecade and since he was very busy, he couldn't give much time to this project. I will be maintaining this project from now on. I will go through the issues on monday. I'll then also release a new version. :)

**Comment by kshvmdn** [comment]
@mrdezzods Great – glad to see this issue led to something! 😃

**Comment by AlmogRnD** [comment]
Not sure I'm going to use it now, but looking forward in seeing some updates

**Comment by arribbar** [comment]
Same answer. I'll help you @mrdezzods on Monday !

**Comment by mrdezzods** [comment]
Closing this issue as I assume it's solved :)

**Comment by lmichailian** [comment]
@mrdezzods this lib are alive?
