### ISSUE TITLE
Swiper not showing

### ISSUE THREAD

**Issue by gianglevan94** [leecade/react-native-swiper#495]
i use react 16.0.0-alpha.12 and react native 0.47.1. And follow Basic Usage but not display everything.  Help me plz. Thank you

**Comment by why-absystem** [comment]
same, change version react-native-swiper@1.5.5

**Comment by gianglevan94** [comment]
@why-absystem thank you. It work like a charm

**Comment by mrdezzods** [comment]
@ahmed3mar , can you look into the issue? It looks like it appeared after we merged ff12771ec12dabcf25e1216bc76db9466c6229e1

**Comment by martinergb** [comment]
Got the same issue

**Comment by taquayle** [comment]
Also have same issue, react-native-swiper 1.5.7, RN 0.47

**Comment by Igor1201** [comment]
Same problem, just after after https://github.com/leecade/react-native-swiper/commit/ff12771ec12dabcf25e1216bc76db9466c6229e1.
Also, if we `setState` on `onIndexChanged` (or `onMomentumScrollEnd`), the Swiper component borks and neither `onIndexChanged` (or `onMomentumScrollEnd`) is called again nor activeDot works anymore.

**Comment by mrdezzods** [comment]
Will make a new release today

**Comment by Igor1201** [comment]
I'm assuming we shouldn't call [`this.setSate` on `componentWillReceiveProps`](https://github.com/leecade/react-native-swiper/commit/ff12771ec12dabcf25e1216bc76db9466c6229e1#diff-1fdf421c05c1140f6d71444ea2b27638R171) if we're not changing the layout.

**Comment by Igor1201** [comment]
anyway we can help, @mrdezzods?

**Comment by lh994749769** [comment]
1.5.8 Still not work

**Comment by d-gubert** [comment]
I had the same issue, but in my case it apparently didn't have something to do with the swiper.

I was trying to use the Swiper inside a tab in the TabNavigator from the [react-navigation](https://github.com/react-community/react-navigation) project, but the swiper wasn't showing up.

After some research and according to [this issue](https://github.com/react-community/react-navigation/issues/662) on their repository, TabNavigator seem to have a problem with "swipeable" children when it has `swipeEnabled: true` and `animationEnabled: true`. The workaround for this case is disabling those options on the navigator. It works, the swiper is shown after setting the options to false, but at the cost of not having the swipe and animation abilities on the navigator, which is a heavy price imo.

I'm still searching for a better solution for the problem, and any help would be appreciated :P

**Comment by denieler** [comment]
I have the same issue, looks like version 1.5.5 solves it, but it also comes with additional bugs.
