### ISSUE TITLE
Only iOS?

### ISSUE THREAD

**Issue by jlsuarezs** [leecade/react-native-swiper#50]
Hi,

I would like to use your component in an Android app, is it possible?

Thank you for your hard work.

J

**Comment by kinhunt** [comment]
+1

**Comment by loox-** [comment]
+1

**Comment by nowittynamesleft** [comment]
+1

**Comment by GasperKolenc** [comment]
It doesn't really work on android. There is no paging, just continuous scroll. Paging buttons also don't work.

**Comment by guanyuxin** [comment]
+1

**Comment by anback** [comment]
+1

**Comment by GasperKolenc** [comment]
For anyone looking for paging functionality, check out this module: https://github.com/race604/react-native-viewpager

**Comment by cgarvis** [comment]
I didn't like the datasource of reac-native-viewpager and it does look like the auther is going to be working on this repo soon, so I built https://github.com/fixt/react-native-page-swiper

**Comment by mhollweck** [comment]
+1

**Comment by rajkissu** [comment]
It's working on Android now, last I checked. Closing this issue.
