### ISSUE TITLE
onIndexChanged only call once after setState

### ISSUE THREAD

**Issue by One28Piece** [leecade/react-native-swiper#506]
### Version
Which versions are you using:

- react-native-swiper v1.5.8
- react-native v0.47.1

### Expected behaviour
onIndexChanged can get index when i swipe ,include setState or mobx chang value

### Actual behaviour
onIndexChanged only call once after setState

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by arribbar** [comment]
Questions:

**Comment by arribbar** [comment]
I do not have this bug with the examples...
Questions:
- can you try it again with version 1.5.9?
- which platform?
- is there an example in which you can reproduce the example ?

**Comment by kyangy** [comment]
@arribbar Was not able to install 1.5.9, couldnt find any versions that match it

**Comment by One28Piece** [comment]
@kyangy use "react-native-swiper": "git+https://github.com/leecade/react-native-swiper.git"

**Comment by One28Piece** [comment]
@arribbar new version fix this bug,thks

**Comment by mrdezzods** [comment]
@One28Piece Glad to hear that :)
