### ISSUE TITLE
newInternals var crashes the app

### ISSUE THREAD

**Issue by vhoen** [leecade/react-native-swiper#507]
Is there any point to this line : https://github.com/leecade/react-native-swiper/blob/feac1487aaa946cc3c516ce72d97f5d16faf9d92/src/index.js#L227

As far as I can see, newInternals is neither declared nor used, furthermore my app crashes because of it.

Am I missing something ?

![capture du 2017-08-10 08-51-12](https://user-images.githubusercontent.com/5245902/29160156-17d2016e-7da9-11e7-90d0-b51afb439b4c.png)

**Comment by arribbar** [comment]
No, there is indeed a bug here
