### ISSUE TITLE
Argument 1 (NSTimeInterval) of RCTTiming.createTimer must not be null

### ISSUE THREAD

**Issue by alvingarcia** [leecade/react-native-swiper#51]
This error appears on swipe:

![screen shot 2015-10-05 at 4 07 01 pm](https://cloud.githubusercontent.com/assets/978771/10275731/64137f58-6b7c-11e5-902f-3be600252f66.png)

Also tried using https://github.com/manandmoon/react-native-swiper but same error appears.

**Comment by leecade** [comment]
try the new version please
