### ISSUE TITLE
Show nothing on RN 0.47.1

### ISSUE THREAD

**Issue by ittianyu** [leecade/react-native-swiper#510]
### Version
Which versions are you using: 

- react-native-swiper v1.5.8
- react-native v0.47.1

### Actual behaviour

It show when I render swiper as an item of FlatList.
But when I render it along, show nothing.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by DigohD** [comment]
I just upgraded from 1.5.4 to 1.5.8 and had the same problem. No pages rendered. I solved this by adding the containerStyle prop to the Swiper and setting it to the following style:

swiperWrapper: {
	flex: 1,
	height: '100%',
	width: '100%',
	alignSelf: 'stretch',
	backgroundColor: '#fff',
}

**Comment by ittianyu** [comment]
@DigohD  Thanks. I'm using react-native-snap-carousel now. It has flatlist version.

**Comment by arribbar** [comment]
With the last version, it should be working. Can you try again @DigohD or @ittianyu ?

**Comment by fungilation** [comment]
Tried on 1.5.9, with and without @DigohD suggestion as new prop to my Swiper:
```javascript
containerStyle={{
  flex: 1,
  height: '100%',
  width: '100%',
  alignSelf: 'stretch',
  backgroundColor: '#fff',
}}
```

Still, the Swiper component doesn't show in my app, with a black bar that was below the Swiper now at the top. As I wrote in https://github.com/leecade/react-native-swiper/issues/494

**Comment by arribbar** [comment]
@fungilation Can you fork the project and reproduce your bug in one of the examples?
I do not succeed to reproduce it on my own...

**Comment by ittianyu** [comment]
Thanks. Works on 1.5.9.
I hope you guys can add a version based on FlatList.

**Comment by arribbar** [comment]
You can work on it if you want to @ittianyu ;)
Or at least, create a new issue.
I closed this one.
