### ISSUE TITLE
in the flatlist, if Swiper is not in the screen, it will not work.

### ISSUE THREAD

**Issue by lizhuoyuan** [leecade/react-native-swiper#513]
in the flatlist, if Swiper is not in the screen,
it will not work.
how do i fix it?

**Comment by arribbar** [comment]
@lizhuoyuan we need more info to help you.
Questions:
- Did you try with the last version 1.5.9 ? If no, can you try with it?
- If the bugs persists, can you fork the project and use an example (or create one) reproducing the bug? It will help us a lot.

**Comment by lizhuoyuan** [comment]
thank you, the problem appeared on Android before.
now , It seems normal.
