### ISSUE TITLE
In flatlist, the contents of swiper are not displayed--android

### ISSUE THREAD

**Issue by lizhuoyuan** [leecade/react-native-swiper#525]
### Which OS ?
android
### Version
Which versions are you using:

- react-native-swiper v1.5.9?
- react-native v0.4.3

### Expected behaviour

![image](https://user-images.githubusercontent.com/15923901/29446407-a05b4ad8-841e-11e7-85d0-1e6e2e52f71d.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/15923901/29446411-a5317708-841e-11e7-8912-f6bf4da0f499.png)

### How to reproduce it>
 <View>
          
                {
                    swiperList.length > 0 ? <View style={styles.interimImgStyle}>
                  
                            <Swiper
                                style={styles.swiper}
                                height={200}
                                horizontal={true}
                                paginationStyle={{bottom: 10}}
                                showsButtons={false}>
                                <Image source={require('../../../foundation/Img/arrow_right.png')} style={styles.img}/>
                                <Image source={require('../../../foundation/Img/arrow_right.png')} style={styles.img}/>
                                <Image source={require('../../../foundation/Img/arrow_right.png')} style={styles.img}/>
                            </Swiper>

                    </View> : null}

### Steps to reproduce
ios is ok , but android .... 
As above

**Comment by lizhuoyuan** [comment]
I'm sorry , in the flatlist is ok

**Comment by MoeMamdouh** [comment]
If the swiper  inside `<scrollView>` or `<ListView>` 
You have to add:
`removeClippedSubviews={false}` to them

**Comment by naivehhr** [comment]
@MoeMamdouh thanks🙂

**Comment by MoeMamdouh** [comment]
@naivehhr  urw bro :)

**Comment by Hari70a** [comment]
@lizhuoyuan 
 Setting height for the swiper fixed the issue for me
