### ISSUE TITLE
Index offset not being calculated on initial render.

### ISSUE THREAD

**Issue by kjkta** [leecade/react-native-swiper#540]
### Which OS ?
iOS / Android

### Version
Which versions are you using:
- react-native-swiper v1.5.10
- react-native v0.47.1

### Expected behaviour
Slide at index prop rendered on initial render.

### Actual behaviour
First slide rendered, then index slide rendered after.

### Steps to reproduce
1. Provide index prop >0
2. Render component

**Comment by arribbar** [comment]
#541 merged
