### ISSUE TITLE
Namespace 'React' has no exported member 'ViewStyle'

### ISSUE THREAD

**Issue by KlimczakM** [leecade/react-native-swiper#542]
### Which OS ?
macOS Sierra 10.12.6

### Version
Which versions are you using:

- react-native-swiper v1.5.10
- react-native v0.44.13

### Expected behaviour

Project with react-native-swiper compiles using typescript. Command: `tsc`.

### Actual behaviour

The command fails with error:

```
$ tsc
node_modules/react-native-swiper/index.d.ts(3,23): error TS2694: Namespace 'React' has no exported member 'ViewStyle'.
node_modules/react-native-swiper/index.d.ts(23,26): error TS2694: Namespace 'React' has no exported member 'ViewStyle'.
node_modules/react-native-swiper/index.d.ts(24,32): error TS2694: Namespace 'React' has no exported member 'ViewStyle'.
node_modules/react-native-swiper/index.d.ts(25,33): error TS2694: Namespace 'React' has no exported member 'ViewStyle'.
error Command failed with exit code 2.
```

### How to reproduce it

Run command: `tsc`. Typescript version: 2.3.4.

### Steps to reproduce
1. `npm i react-native-swiper --save` OR `yarn add react-native-swiper`
2. `tsc`

When I open a `react-native-swiper/index.d.ts` file in my IDE (IntelliJ) I can see the error as well:
![github](https://user-images.githubusercontent.com/7666098/29760717-6a612732-8bc5-11e7-9348-b9c6393ba3f3.png)

**Comment by notDying** [comment]
Similar issue we are facing with following configurations.
react-native-swiper v1.5.4
react-native v0.40.0
MAC OS v 10.12.6

**Comment by ouss-athome** [comment]
Similar issue here...
react-native-swiper v1.5.10
react-native v0.47.2

**Comment by doliawu** [comment]
+1

**Comment by arribbar** [comment]
Done in https://github.com/leecade/react-native-swiper/pull/546
