### ISSUE TITLE
Warning: Failed prop type: Invalid prop `style` supplied to `_class`.

### ISSUE THREAD

**Issue by xiaobai1990zhan** [leecade/react-native-swiper#543]
### Version
- react-native-swiper v1.5.10

### Code
`<Swiper loop={false}>XXXXX</Swiper>`
I didnot write any styles, but it warning.

![image](https://user-images.githubusercontent.com/8044879/29762756-b5e0b53c-8c02-11e7-9ef2-82ab185dbcfe.png)

**Comment by arribbar** [comment]
I do not have any warning with no style in my swiper.
Can you fork the project and reproduce your warning in an example ?

**Comment by fabiorbap** [comment]
I second @xiaobai1990zhan problem, I'm using the styled components lib, I'm not sure if it's related.

```export const OnboardTutorialViewPager: any = styled(ViewPager)`
`;```

And in the component render method

```render() {
    return (
      <OnboardTutorialViewPager>
        <OnboardTutorialPageStyled>
          <OnboardTutorialImageStyled
            source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Nietzsche187c.jpg/170px-Nietzsche187c.jpg' }}
          />
        </OnboardTutorialPageStyled>
        <OnboardTutorialPageStyled>
          <OnboardTutorialImageStyled
            source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Nietzsche187c.jpg/170px-Nietzsche187c.jpg' }}
          />
        </OnboardTutorialPageStyled>
        <OnboardTutorialPageStyled>
          <OnboardTutorialImageStyled
            source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Nietzsche187c.jpg/170px-Nietzsche187c.jpg' }}
          />
        </OnboardTutorialPageStyled>
      </OnboardTutorialViewPager>
    );
  }```

**Comment by gazedash** [comment]
It also complains about array of styles.

**Comment by artificis** [comment]
I'm experiencing a similar issue here. No warnings without any style though. But it complains if I assign custom styles, either `style`, `activeDotStyle`, or `dotStyle`.

**Comment by damianfarina** [comment]
Don't know what's the issue with array of styles, but here is a workaround:
This piece of code
```
style={[firstStyle, secondStyle]}
```
is equivalent to
```
style={StyleSheet.flatten([firstStyle, secondStyle])}
```
and the warning is gone.

**Comment by kaladivo** [comment]
I get the same warning with styled-components.

**Comment by Danny-weebo** [comment]
I'm getting the same warning using styled-components,
```Warning: Failed prop type: Invalid prop `style` supplied to `_class`.```

```
const SwiperView = styled(Swiper)``;
```

versions
RN: 0.55.4,
React: 16.3.1,
react-native-swiper: 1.5.13

**Comment by ammichael** [comment]
I'm also having this issue with styled-components. Any update on this?

**Comment by ammichael** [comment]
@leecade sorry to bring you up here, but I'm pretty sure this fix is something really quick for someone skilled enough to put this lib together. this warning has been haunting my console for a while now. could you please help out the poors using styled components together with swiper?

thanks a lot!

**Comment by caferyukseloglu** [comment]
That is still a thing
