### ISSUE TITLE
Slider does not show although I see it in devtools. 

### ISSUE THREAD

**Issue by tokict** [leecade/react-native-swiper#553]
The code worked with 1.5.4.
I just updated to newest ones and discovered nothing above 1.5.5 works

### Which OS ?
Android
### Version
Which versions are you using:
7.0
- react-native-swiper v?
any above 1.5.5
- react-native v0.?.?
48.0
### Expected behaviour
Render swiper 

### Actual behaviour
No swiper

### How to reproduce it
It cant even render basic default swiper with two slides that were working before.
-

### Steps to reproduce
1.Create slider
2.Put 2 slides
3.Try to run

**Comment by nimatrueway** [comment]
I got this problem too. Make parent views of `<Swiper>` fill the whole screen (maybe using `flex: 1`) plus, add property `removeClippedSubviews={false}` to Swiper too. This way at least all screens show up.

My problem is still with the swiping it self which is not working. 🤔

**Comment by arribbar** [comment]
Have you tried with the latest version, 1.5.12? @nimatrueway and @tokict 
Can you show some code by forking the project and reproducing the bug in you forked project?
If you have a solution working, PR are welcome

**Comment by tokict** [comment]
Setting the parent height fixes the issue. It is still present in 1.5.12.
