### ISSUE TITLE
Script in the example makes simulator run slow. 

### ISSUE THREAD

**Issue by Asker109** [leecade/react-native-swiper#557]
The script -  react-native-swiper/examples/scripts/watch-and-copy-src.js makes the simulator lag. It happens universally to all apps now.

How can I  undo the script and return to normal simulator functioning?

### Version
Which versions are you using:

### Expected behaviour

React-Native apps do not lag and work as the originally did. 

### Actual behaviour

React-Native apps lag because of the script.

**Comment by arribbar** [comment]
Hmm, instead of using it, you can, for each change in src, do 
` rm -rf node_modules; yarn;`
