### ISSUE TITLE
Custom buttons color

### ISSUE THREAD

**Issue by pensierinmusica** [leecade/react-native-swiper#558]
Hi,

How do you change the color of the buttons? I need it to be the same as the color of the dots, which I modified from the default value.

Shall we have a simple property `buttonColor`, like the existing `dotColor`?

Or should simply `dotColor` be renamed to `controlColor` and automatically apply the indicated color to the buttons and the dots?

Look forward to hearing your thoughts, cheers!

**Comment by arribbar** [comment]
Just a new property buttonColor would be ok.
Can you make a new PR, @pensierinmusica  ?

**Comment by pensierinmusica** [comment]
Done  :)

**Comment by Calsowah** [comment]
How do you actually invoke this property. I have tried 
```
<Swiper
buttonColor={'#DDD'} 
> 
</Swiper>
```
But it still chooses to remain blue. I'm on android

**Comment by pensierinmusica** [comment]
@Calsowah ...waiting for this pull request to be merged (since a year): https://github.com/leecade/react-native-swiper/pull/562/
