### ISSUE TITLE
Element type is invalid on RN 0.46

### ISSUE THREAD

**Issue by nomoreboredom** [leecade/react-native-swiper#565]
### Which OS ?
iOS
### Version
Which versions are you using:

- react-native-swiper v1.5.12
- react-native v0.46

### Expected behaviour

Should work

### Actual behaviour

It is throwing the error:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

**Comment by nomoreboredom** [comment]
Anybody did manage to make it work on RN 0.46?

**Comment by nomoreboredom** [comment]
Had to change the import to
```import * as Swiper from 'react-native-swiper';```
in my case, closing the issue.

**Comment by vlerants** [comment]
Any solution for this?
