### ISSUE TITLE
react-native 0.48.3 and react-native-swiper - Last slide shown first

### ISSUE THREAD

**Issue by nixoz** [leecade/react-native-swiper#570]
### Which OS ?
IOS

### Version
Which versions are you using:

- react-native-swiper v1.5.12 (but it affect every single version of it, tried back to 1.5.4 as well)
- react-native v0.48.3

### Expected behaviour

- The first slide should be first.

### Actual behaviour

- The last slide showed first.
- Awkward pagination display - it shows the state of the first slide, while displaying the last slide.

p.s. If loop={false} is set - everything seems fine.

### How to reproduce it>
Just get the repo from
https://github.com/nixoz/swiperDemo
-

### Steps to reproduce
1. Create mint react-native project
2. Copy paste first example from react-native-swiper README
3. react-native run-ios
4. KABOOM!

**Comment by nixoz** [comment]
UPD: I guess it related with https://github.com/facebook/react-native/issues/15808

**Comment by mtt87** [comment]
Yes it's a regression, not working also on RN 0.46

**Comment by longsangstan** [comment]
not working also on RN 0.44

**Comment by BenoitClaveau** [comment]
Have you try with loop=false ?

**Comment by kdong007** [comment]
same issue here

**Comment by BenoitClaveau** [comment]
The bug is here
if (loop) {
        pages.unshift(total - 1 + '')
        pages.push('0')
}

pages is modified but index is not updated. So the "current" page change.

**Comment by 1uokun** [comment]
Still exists in iOS whatever version.
Can you tell me what is the action in this step to update in `Line 329`?
https://github.com/leecade/react-native-swiper/blob/f00abfb859ce384be2003cfce3010c3fc0005be1/src/index.js#L324-L330

When I change the code,It works as well as Android

```
- this.setState(state)
+ Platform.OS !== 'ios'&&this.setState(state)
```
