### ISSUE TITLE
when I wanted to change autoplay, it doesn't work

### ISSUE THREAD

**Issue by lizhuoyuan** [leecade/react-native-swiper#575]
### Which OS ?
android,ios
### Version
Which versions are you using:

- react-native-swiper 1.5.10?
- react-native v0.43.1

### Expected behaviour

Want to control swiper's autoplay at any time

### Actual behaviour

Only changed once, again changed swiper no response
### How to reproduce it>

this.state={
swiperAutoplay:true
}

<Swiper
                            autoplayTimeout={4}
                            loop={true}
                            autoplay={this.state.swiperAutoplay}
                      >
Opacity:
                this.setState({
                    swiperAutoplay: !this.state.swiperAutoplay
                });
then swiperAutoplay = false,
and swiper does not scroll automatically,

but Opacity angin:
then swiperAutoplay = true,
swiper still does not scroll automatically,

**Comment by ifours** [comment]
You can use <Swiper ref={node => this.swiper = node} />. And after that this.swiper.autoplay()

**Comment by lizhuoyuan** [comment]
@ifours 
<Swiper
                               ref={node => this.swiper = node} 
                                autoplayTimeout={4}
                            
                                autoplay={false}
                            >

this.swiper.autoplay()
this isn't work

**Comment by ifours** [comment]
You should set `autoplay={true}` before `this.swiper.autoplay()`. Like that `this.setState({ swiperAutoplay: true }, () => { this.swiper.autoplay() ;})`

**Comment by lizhuoyuan** [comment]
@ifours  Thank you very much!

**Comment by roysG** [comment]
First of all, many Thanks!!
Second, what are the difference betweens the codes:

Code 1: - WORKS:
 this.setState({autoPlay:true},() => { this.swiper.autoplay() ;})

Code 2: - Not Works:
 this.setState({autoPlay:true})
this.swiper.autoplay();

???

**Comment by ifours** [comment]
@roysG in first case you will call `autoplay` after swiper receives `autoplay={true}`

**Comment by roysG** [comment]
I tried to modified a bit the code and simulate it with setTimeout, without success, maybe you know why?
According to what you said i fired the "autoplay()" function after i set the "autoPlay" to true.

  this.setState({autoPlay:true});
                                      setTimeout(()=>{
                                          for(let item in this._xxx) {

                                              if(this._xxx[item] && typeof this._xxx[item].autoplay === 'function')
                                                  this._xxx[item].autoplay();
                                          }

                                      },1500);

**Comment by roysG** [comment]
Thanks.
