### ISSUE TITLE
How do I create spacing between two sliders? 

### ISSUE THREAD

**Issue by hannahblair** [leecade/react-native-swiper#576]
Hiya - I'm trying to create some kind of spacing between two sliders as currently they are merged when you slide them. Is there a prop to apply here? Couldn't find it myself.

Thanks in advance. 

<img width="161" alt="screen shot 2017-09-18 at 17 52 41" src="https://user-images.githubusercontent.com/15165908/30551672-822e3972-9c9b-11e7-8c6e-a5a3c4e0118c.png">

**Comment by Tom29** [comment]
Have you find a solution yet?

**Comment by hannahblair** [comment]
Nope, not yet.

**Comment by arribbar** [comment]
I have never tried to do this with this project. I do not think it is possible yet. Currently, we take the width of one slide and add it to the current view to go to the next slide.
One solution is to work on this new feature by yourself.
The other solution is to try this [project] (https://js.coach/react-native/react-native-snap-carousel?search=slider)

**Comment by jitendraheaptrace** [comment]
Facing same issue
