### ISSUE TITLE
bug in showing the custom index after updating from 1.5.11 to 1.5.12

### ISSUE THREAD

**Issue by BatDroid** [leecade/react-native-swiper#577]
### Which OS ?
ios- android
### Version
Which versions are you using:

- react-native-swiper v?
1.5.12
- react-native v0.?.?
0.48.2
### Expected behaviour
giving index property give the page related to that index

### Actual behaviour
although the dot is on the desired index but the page that is shown is the page related to the most left page (index = 0)

### How to reproduce it>
To help us, please fork this component, modify one example in examples folder to reproduce your issue and include link here.
- just updating from the 1.5.11 to 1.5.12 made this issue and when i reverted to the 1.5.11 it worked again.

**Comment by luqmanrom** [comment]
I think it is 1.5.10 instead of 1.5.11 right? I had the same issues

**Comment by Paul-Todd** [comment]
I had to downgrade to 1.5.10 which fixed the issue for me

**Comment by arribbar** [comment]
Can you try again with version 1.5.13, please and tell me if it does it again.

**Comment by BatDroid** [comment]
i updated to 1.5.13 and everything seems to work fine... thanks 👍
