### ISSUE TITLE
Upgrade from 1.5.10 to 1.5.11: getting white screen when switching to a tab 

### ISSUE THREAD

**Issue by yenda** [leecade/react-native-swiper#584]
### Which OS ?

Android

### Version
Which versions are you using:

- react-native-swiper v1.5.11
- react-native v0.43.4

### Expected behaviour

Can change tabs like in v1.5.10

### Actual behaviour

Getting a white screen

### How to reproduce it

I created a more detailed issue in our project tracker regarding this issue:
https://github.com/status-im/status-react/issues/1915

**Comment by nertilzhuri** [comment]
I am having the same issue. It appears that the swiper element does not work with "flex: 1" on it's style.

<Swiper style={{flex: 1...}} ... </Swiper>

Not using flex fixed the issue for me. I hope this helps.

**Comment by arribbar** [comment]
@yenda Did you try @nertilzhuri's solution ? 
Also, can you try with our latest version 1.5.13?

**Comment by yenda** [comment]
I tried both but the problem arises because the swiper is within react-native-drawer-layout (https://github.com/react-native-community/react-native-drawer-layout). If I take it out it works fine.

**Comment by spotsadmin** [comment]
@arribbar Seems to be happening with version 1.5.13 also. Works ok in iOS. Issue is in Android.
```
  react: 16.0.0-alpha.12
  react-native: 0.48.4
```

**Comment by yenda** [comment]
This was fixed by a refactoring on our side (see issue linked in my OP)

**Comment by saigyouyou** [comment]
I just encount the same problem. I change 'flex:1' to fixed width and height, but it doesn't work.
Is there some simple way to solve it ?
@leecade
