### ISSUE TITLE
Is it possible build something like this??

### ISSUE THREAD

**Issue by soyjavi** [leecade/react-native-swiper#585]
Hi,

My idea is use your component, but I need a specific behavior. I would like to see on the screen part of the next element:
![screen shot 2017-09-24 at 1 44 13 pm](https://user-images.githubusercontent.com/559654/30780147-86edad70-a12e-11e7-8731-f3d449837af3.png)

Do you have any idea how can i do it?

**Comment by benqy** [comment]
change <ViewPagerAndroid> to <scorllview> in line 602.
and set pagingEnabled = false

**Comment by soyjavi** [comment]
The idea is continue with `paging` just wanna show more elements. is it possible?

**Comment by soyjavi** [comment]
Hey... any idea?

**Comment by arribbar** [comment]
Hey @soyjavi, 
It seems a bit hard with this project. You might want to take a look at this [project](https://js.coach/react-native/react-native-snap-carousel?search=slider)
