### ISSUE TITLE
Swiper on IOS with react navigation not working

### ISSUE THREAD

**Issue by jjdp** [leecade/react-native-swiper#591]
### Which OS ?
IOS
### Version
Which versions are you using:

- react-native-swiper: 1.5.12
- react-native v0.47

### Actual behaviour
I'm push a stack as my "PhotoView" so the user can view the photo in full screen. Swiping works fine on android. On IOS, it doesn't swipe at all. I also disabled the gestures on StackNavigator. Any else experience this? Using the latest .13 beta of react navigation btw

**Comment by jjdp** [comment]
apparently caused by flex, setting to devicewidth worked

**Comment by Mimicx** [comment]
i have the same issue, where do you setting the width?

**Comment by igorlifar** [comment]
+1, I have the same issue.

**Comment by nicollasmatheus** [comment]
Any solutions?

**Comment by slava-ovchinnikov** [comment]
Any solutions?

**Comment by kishanbharda** [comment]
Add `removeClippedSubviews={false}`  props to `<Swiper>` component. It will work.

```
<Swiper
    style={{}}
    removeClippedSubviews={false} // <== Add this
>
    <Component />
    ...
    ...
</Swiper>
```
