### ISSUE TITLE
Swiper don't show until a touch it

### ISSUE THREAD

**Issue by EQuimper** [leecade/react-native-swiper#593]
On Ios

- react-native-swiper v1.5.12?
- react-native v0.48.4

In my app I got a weird problem. The swiper don't show until I do some gesture on it. The weird thing is I didn't get this problem when with react-navigation@beta 13 I was using the screen with the swiper as the initialRouteName.

Look like the component don't mount or something like that in the stack navigator. Like I say until I touch it I cannot see nothing.

Here a video about this https://drive.google.com/open?id=0B-wdzKw8lrR8VmFJZnJ6S0dUOTg

```js
<Swiper {...swiperOpts} ref={ref => (this.swiper = ref)}>
          {relaxationsData.map((item, i) => {
            if (i === 0) {
              return (
                <Step1
                  currentIndex={i}
                  key={i}
                  onNextPress={this._onNextPress}
                />
              );
            }
            return (
              <CommonsStep
                actionNumber={i + 1}
                currentIndex={i}
                item={item}
                key={i + 1}
                onNextPress={this._onNextPress}
              />
            );
          })}
        </Swiper>
```

**Comment by IjzerenHein** [comment]
Try adding the `removeClippedSubviews={false}` prop to `Swiper`

**Comment by EQuimper** [comment]
@IjzerenHein Thank you that worked now :)
