### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by benjamingeorge** [leecade/react-native-swiper#6]
I just tried your example and I get this error in the console.
 
"Warning: Failed propType: Invariant Violation: index: prop type `renderPagination` is invalid; it must be a function, usually from React.PropTypes. "

I'm following your "Basic usage" in the readme.md so I'm not passing anything to renderPagination. I wonder if it's in your lib code?

**Comment by leecade** [comment]
ok I defined a wrong type :(

fixes later.
