### ISSUE TITLE
Swiper fails to 'snap' to slides on android

### ISSUE THREAD

**Issue by MossP** [leecade/react-native-swiper#60]
On android swiping does not snap to the edges of each slide. It simple stops where the swipe ends.

**Comment by charmingzuo** [comment]
+1

**Comment by chenchen1008** [comment]
++

**Comment by leecade** [comment]
next version to support android.

`v1.4.0` contains a [PR](https://github.com/leecade/react-native-swiper/pull/73)

> add simple support for android

you may try it and PR is welcome

**Comment by divyekhanna** [comment]
@leecade @MossP This issue still persists for me. I'm using v1.4.8

The swiper randomly stops snapping to slides on Android.

**Comment by brandonfancher** [comment]
Same here. When it first renders, snapping works fine. If I got to another route/scene and then come back, snapping no longer works.

**Comment by tjlian616** [comment]
The issue is still here as of 1.5.13. The first rendering is fine. It breaks if you leave and come back.

**Comment by tjlian616** [comment]
the issue was discussed here and there is couple workarounds.
https://github.com/wix/react-native-navigation/issues/1317

**Comment by isaacalves** [comment]
> (...) swiping does not snap to the edges of each slide. It simple stops where the swipe ends.

I get exactly that, on iOS Chrome and Safari. Not using React (or React-native), just plain JavaScript.

It works after I swipe down though.
