### ISSUE TITLE
loop disable nextButton in last screen

### ISSUE THREAD

**Issue by jose-fernandez** [leecade/react-native-swiper#610]
When loop is activated, by default disable prevButton in the first screen and nextButton in last screen. Does anyone know any way to force them to appear?

```es2015
    <Swiper
          showsButtons
          loop={false}
          showsPagination
          bounces
          buttonWrapperStyle={style.buttonWrapperStyle}
          paginationStyle={style.paginationStyle}
          removeClippedSubviews
          activeDot={<View style={style.activeDot} />}
          nextButton={
            <Text
              style={{
                fontSize: 16,
                color: '#767676',
                fontWeight: 'bold',
                padding: 20,
              }}
              onPress={done ? this.handleFinishPress : null}
            >
              {txt}
            </Text>
          }
          prevButton={
            <Text
              onPress={this.handleFinishPress}
              style={{
                fontSize: 16,
                color: '#767676',
                fontWeight: 'bold',
                padding: 20,
              }}
            >
              Skip
            </Text>
          }
          onIndexChanged={index => {
            console.log(index);
          }}
        >
```
![screen shot 2017-10-12 at 13 55 11](https://user-images.githubusercontent.com/22930011/31494901-9a9ff60e-af55-11e7-94f2-f94f634f9da0.png)
![screen shot 2017-10-12 at 13 55 23](https://user-images.githubusercontent.com/22930011/31494910-9f5c5f84-af55-11e7-88c5-c2505af1d36f.png)

**Comment by danielekpa** [comment]
Hi Jose, this comment is definitely 6 years too late. I had the same issue with you, needed the control buttons to be static and sticky but it just wasn't working. 

2 options. 1). Rewire the package. 2) Work around the package. 

I went with option 2 and built my own buttons and placed them in a View and put the view below the Swiper component with absolute positioning, and you're good to go.
