### ISSUE TITLE
Set index not working properly on Android

### ISSUE THREAD

**Issue by xshadowlegendx** [leecade/react-native-swiper#621]
### Which OS ?
Android
IOS - Working Fine

### Version
Which versions are you using:

- react-native-swiper v1.5.13
- react-native v0.49.3

### Expected behaviour

Go to next slide

### Actual behaviour

Stayed on same slide

### Steps to reproduce
1. Click on button that set state index + 1
2. Slide goes to next index which shown by the pagination
3. Slide content are the same

When i tried enable the scrolling, I could scroll and saw the content of next slide. I want to trigger the slide by my own button.
Here is the option on the Swiper
```
<Swiper

    autoplay={ false }
    style={ styles.wrapper }
    showPagination
    loop={ false }
    showButtons={ false }
    activeDotColor={ 'black' }
    index={ this.state.index }
    paginationStyle={ styles.paginationStyle }

>...
```

**Comment by xshadowlegendx** [comment]
Never mind, using ref and scroll by instead of setting state works.

**Comment by xshadowlegendx** [comment]
Wait I cannot go back by doing ``this.refs.swipper.scrollBy( index - 1, true )`` ?

**Comment by xshadowlegendx** [comment]
Never mind, i found it in issue to do it scrollBy ( -1 )

**Comment by zhengzhuoxing** [comment]
![image](https://user-images.githubusercontent.com/19711700/41093446-e7fccf9c-6a7d-11e8-89b3-a2feb2eebb5b.png)
添加这些代码就好了
`if (this.initialRender && this.state.total > 1) {
        this.scrollView && this.scrollView['setPage'](this.state.index)
        this.initialRender = false;
      }`
