### ISSUE TITLE
when TabNavigator are nested，the react-native-swiper in the inner TabNavigator can‘t show 

### ISSUE THREAD

**Issue by AKMaS** [leecade/react-native-swiper#625]
just like this,the top TabNavigator  is the inner  .

![wx20171024-180835](https://user-images.githubusercontent.com/14304498/31937238-649ccc0e-b8e6-11e7-9b26-5b2dd79fd1d8.png)

**Comment by AKMaS** [comment]
but  it  look normal  without  the inner TabNavigator....
![wx20171024-181231](https://user-images.githubusercontent.com/14304498/31937469-1b19a4ac-b8e7-11e7-88ab-f941ab673eb0.png)

**Comment by hoscarcito** [comment]
same, but I'm using react-native-scrollable-tab-view
Did you try rotating the device? it works for me but its anoying. 
I guess its something from Android, 'cause its not happening on iOS

**Comment by Mttylzq** [comment]
I use it in IOS, the same question.

**Comment by astrocket** [comment]
same here 

  "dependencies": {
    "axios": "^0.16.2",
    "impagination": "^1.0.0-alpha.3",
    "mobx": "^3.3.1",
    "mobx-react": "^4.3.3",
    "native-base": "^2.3.3",
    "react": "16.0.0-beta.5",
    "react-native": "0.49.3",
    "react-native-billing": "^2.4.0",
    "react-native-fbsdk": "^0.6.3",
    "react-native-keyboard-aware-scroll-view": "^0.3.0",
    "react-native-root-toast": "^1.3.0",
    "react-native-swiper": "^1.5.13",
    "react-native-textinput-effects": "^0.4.1",
    "react-native-vector-icons": "^4.4.2",
    "react-navigation": "^1.0.0-beta.13"
  },

**Comment by lilin666** [comment]
@hoscarcito I‘d also encountered the same question

**Comment by guoguo0202** [comment]
try  animationEnabled: false,
       swipeEnabled: false,

add to `TabNavigatorConfig`

**Comment by sunnynegi** [comment]
@guoguo0202  Done the same configuration with tab but, still have a same problem. Swiper is moving slow, when you try to slide the content.

**Comment by guoguo0202** [comment]
@sunnynegi     remove `animationEnabled: false,   swipeEnabled: false,` ，   useing  `setTimeout` to delay rendering `Swiper`
export class SwiperDemo extends Component {
    constructor(props) {
        super(props);
        this.state = {
            swiperShow:false,
        };
    }
  componentDidMount(){
        setTimeout(()=>{
            this.setState({
                swiperShow:true
            });
        },0)
    }
   render() {
        if(this.state.swiperShow){ 
            return(
                <Swiper>
                  ...
                </Swiper>
            )
        }else {
            return (
                <View></View>
            );
        }
    }
}

**Comment by Mixpeal** [comment]
@guoguo0202 , your solution works for me
