### ISSUE TITLE
UnableToResolveError: Unable to resolve module Dimensions from /Users/.../dev/reactnative/App/node_modules/react-native-swiper/dist/index.js

### ISSUE THREAD

**Issue by jedrekk** [leecade/react-native-swiper#63]
I'm getting a 

> UnableToResolveError: Unable to resolve module Dimensions from /Users/JohnSmith/dev/reactnative/App/node_modules/react-native-swiper/dist/index.js: Invalid directory /Users/node_modules/Dimensions

when I try to use the npm module in my app.

Is this tied to the change in imports in React Native 0.14?

OS X 10.11.1, Xcode Version 7.1.1 (7B1005), React Native 0.14.2

**Comment by jedrekk** [comment]
I've filed a pull request to fix this

https://github.com/leecade/react-native-swiper/pull/64

**Comment by AliThink** [comment]
Same problem , how to fix it..

**Comment by nodkrot** [comment]
+1

**Comment by pmpSalween** [comment]
Have you tried this... I am using React-Native version 0.15.0

    var {Dimensions} = _reactNative; (or) _React$StyleSheet$Text$View$ScrollView$TouchableOpacity;
    var {width, height} = Dimensions.get('window');

**Comment by stereodenis** [comment]
same problem

**Comment by guzijiang** [comment]
same problem

**Comment by nodkrot** [comment]
I have a feeling it'll be easier to implement the swiper yourself, 
Example: https://github.com/nick/react-native-carousel/blob/master/Carousel.js

**Comment by wenkangzhou** [comment]
#64 can solve the problem.

**Comment by nodkrot** [comment]
When is it going to be merged?

**Comment by agolovenko** [comment]
+1 need this

**Comment by leecade** [comment]
fixed `v1.4.0`
