### ISSUE TITLE
react-native 0.14.2 the swiper is broken

### ISSUE THREAD

**Issue by dongtong** [leecade/react-native-swiper#65]
I used lastest react native(0.14.2) and lastest react-native-swiper, I found the swiper is broken, cannot swipe.

the implement as fowllowing:
------

'use strict';

import React from 'react-native';
import Swiper from 'react-native-swiper';

let {
  View,
  Component,
  Image,
  StyleSheet,
  Text
} = React;

let styles = StyleSheet.create({
  //slider
  wrapper: {
      height:80
  },
  slide: {
      height:80,
      resizeMode: Image.resizeMode.contain
  }
});

let sliderImgs = [
  'http://images3.c-ctrip.com/SBU/apph5/201505/16/app_home_ad16_640_128.png',
  'http://images3.c-ctrip.com/rk/apph5/C1/201505/app_home_ad49_640_128.png',
  'http://images3.c-ctrip.com/rk/apph5/D1/201506/app_home_ad05_640_128.jpg'
];

class Slider extends Component {
  render() {
    return (
      \<Swiper style={styles.wrapper} showsButtons={false} autoplay={true} showsPagination={false}>
        \<Image style={styles.slide} source={{uri: sliderImgs[0]}}></Image>
        \<Image style={styles.slide} source={{uri: sliderImgs[1]}}></Image>
        \<Image style={styles.slide} source={{uri: sliderImgs[2]}}></Image>
      \</Swiper>
    );
  }
}

export {Slider};

---

the display as vertical layout:

\<img ... />
\<img ... />
\<img ... />

**Comment by Cocoon-break** [comment]
same problem,but some times is  horizontal layout

**Comment by mhollweck** [comment]
+1

**Comment by leecade** [comment]
fixed `v1.4.0`, sorry for that.
