### ISSUE TITLE
How to show 2 item in one slide

### ISSUE THREAD

**Issue by DevGentle** [leecade/react-native-swiper#658]
### Which OS ?
Both `ios` and `android`

### Version
Which versions are you using:

- react-native-swiper `latest-version`
- react-native `v0.49.5`

### Question
Is it possible to show 2 items in one slide like image below

<img width="295" alt="screen shot 2560-11-13 at 10 50 23 pm" src="https://user-images.githubusercontent.com/20085539/32734631-2274b898-c8c5-11e7-8cfe-f78ffe45d66c.png">

How to do something like this image ?

Thanks !

**Comment by angryanatole** [comment]
@DevGentle if I understood your question correctly, you could make a wrapper component, which will wrap these two items. Something like
`<View style={{flex: 1, flexDirection: 'row'}}>`
`<ComponentOne>`
`<ComponentTwo>`
`</View>`

**Comment by DevGentle** [comment]
Thx for the answer.
