### ISSUE TITLE
lottie-react-native don't show in the swiper

### ISSUE THREAD

**Issue by MatthieuPeyrot** [leecade/react-native-swiper#670]
Hi i try to add an animation in the swiper using lottie.  https://github.com/airbnb/lottie-react-native
But it doesn't show the animation in the swipper instead i have a transparent shape.

**Comment by lenguyenthanh** [comment]
@MatthieuPeyrot How is this going? Did you find a solution for it? Thanks!

**Comment by MatthieuPeyrot** [comment]
@lenguyenthanh no i didn't

**Comment by lenguyenthanh** [comment]
@MatthieuPeyrot Thanks for answering my question. I'm going to work with it. If I find something I'll let you know.

**Comment by MatthieuPeyrot** [comment]
@lenguyenthanh Thanks for looking into it

**Comment by MatthieuPeyrot** [comment]
@lenguyenthanh any news ?

**Comment by tutts** [comment]
Hey, I was looking through issues to find something unrelated, but saw this thread and we have Lottie working in our slider, post up some code and I'll see if I can help 👍

**Comment by MatthieuPeyrot** [comment]
<Swiper
            showsButtons={true}
            activeDotColor={'#FFFFFF'}
            dotColor={'#FFFFFF40'}
            nextButton={<Text style={styles.buttonText}>›</Text>}
            prevButton={<Text style={styles.buttonText}>‹</Text>}
          >
            <View style={styles.backgroundOpacity}>
              <View style={styles.logoBox}>
                <Animation
                  loop={true}
                  ref={animation => (this.animation = animation)}
                  style={{
                    width: 200,
                    height: 200
                  }}
                  source={jsonLottie}
                />
              </View>
              <View style={styles.bottomPage}>
                <Text allowFontScaling={false} style={styles.bottomText}>
                  {strings.first_use_main_slide_read}
                </Text>
              </View>
            </View>
            <View style={styles.backgroundOpacity}>
              <View style={styles.logoBox}>
                <Animation
                  loop={true}
                  ref={animation => (this.animation = animation)}
                  style={{
                    width: 200,
                    height: 200
                  }}
                  source={jsonLottie}
                />
              </View>
              <View style={styles.bottomPage}>
                <Text allowFontScaling={false} style={styles.bottomText}>
                  {strings.first_use_main_slide_perso}
                </Text>
              </View>
            </View>
          </Swiper>

const styles = {
  buttonText: {
    color: '#FFFFFF',
    backgroundColor: 'transparent',
    fontSize: 50,
    textAlign: 'center',
    fontFamily: 'Lato-Regular'
  },
  backgroundOpacity: {
    alignItems: 'center',
    justifyContent: 'space-around'
  },
  bottomPage: {
    paddingLeft: 30,
    paddingRight: 30
  },
 logoBox: {
    paddingTop: 20
  } 
}

**Comment by tutts** [comment]
we have a similar implementation, although we make use of the `Animation` library, might make a difference here?

set the progress in state (or static prop if you're using appropriate babel stage presets)

```javascript
  constructor(props) {
    super(props)
    this.state = {
      progress: new Animated.Value(0),
    }
  }
```

on transition we needed to reset and force update (think this was a workaround)

```javascript
  componentWillUpdate(nextProps) {
    if (nextProps.currentActiveSlide !== this.props.currentActiveSlide) {
      this.state.progress.setValue(0)
      Animated.timing(this.state.progress, {
        toValue: 1,
        duration: 5000,
      }).start(({ finished }) => {
        if (finished) this.forceUpdate()
      })
    }
  }
```

```javascript
render() {
  <Animation ref={this.setAnim} style={styles.slideImage} source={image} progress={this.state.progress} />
}
```

the styling is a basic flex:

```javascript
  slideImage: {
    flex: 1,
  },
```

hope that helps

**Comment by MatthieuPeyrot** [comment]
no it doesn't work 
even without the animation the lottie file don't show in the slider , it's invisible.
and if put it outside of the slider the lottie file work but inside it's invisible

**Comment by MatthieuPeyrot** [comment]
Something even weirder, on Android, if I swipe fast enough, I can see the animation 1ms before disappear

**Comment by MatthieuPeyrot** [comment]
when I remove this line of code 

` this.loopJumpTimer = setTimeout(() => scrollView.setPageWithoutAnimation &&
      scrollView.setPageWithoutAnimation(i), 50)`

when I swipe once, it appears

**Comment by MatthieuPeyrot** [comment]
Ok i have the solution it works, it was me, I changed the way of looping the animation

**Comment by tjlian616** [comment]
@MatthieuPeyrot  would you please share your solution? I'm having the same issue with lottie. The area is just transparent and I see no warnings in logs anywhere.

**Comment by MatthieuPeyrot** [comment]
@tjlian616 I just change the way I did the animation, I create a special PureComponent for solving this.

`  componentDidMount() {
    setTimeout(() => {
      if (this.animation) {
        this.animation.play()
      }
    }, 0)
  }`

`
  play = () => {
    if (this.animation) {
      this.animation.play()
    }
  }`
`  reset = () => {
    if (this.animation) {
      this.animation.reset()
    }
  }`

` <Animation
          ref={animation => {
            this.animation = animation
          }}
        />`
