### ISSUE TITLE
unsupported

### ISSUE THREAD

**Issue by wuchuguang** [leecade/react-native-swiper#69]
npm i react-native-swiper --save
npm WARN install Couldn't install optional dependency: Unsupported
reactProject2@0.0.1 /opt/reactProject2
└── react-native-swiper@1.3.0 

[root@real-server-04 reactProject2]# node -v
v5.1.0

**Comment by leecade** [comment]
not sure, try:

```
npm init
npm i react-native-swiper --save
```

may new version fixed
