### ISSUE TITLE
ScrollResponders are not supported

### ISSUE THREAD

**Issue by smothers** [leecade/react-native-swiper#7]
ScrollResponders are documented in the readme, but onMomentumScrollEnd along with the other responders throw invalid property errors when added to a Swiper.

**Comment by smothers** [comment]
Went from 1.0.4 to 1.1.1 and that got rid of the error.

Now it just looks like https://github.com/leecade/react-native-swiper/blob/master/dist/index.js#L224 needs to be:

```javascript
this.props.onMomentumScrollEnd && this.props.onMomentumScrollEnd.call(this, e);
```

so we can access the event context.

**Comment by smothers** [comment]
Adding the index would be really useful:
```javascript
this.props.onMomentumScrollEnd && this.props.onMomentumScrollEnd.call(this, e, this.state.index);
```

**Comment by leecade** [comment]
cool, you are right, i forget the event param.

**Comment by leecade** [comment]
New version(1.2.0) fixed this issue, thank you for point this, and maybe get `index` like this `this.state.index` is better.

**Comment by smothers** [comment]
@leecade Thanks for the quick fix!

I don't think React wants you to [change context between components](https://groups.google.com/d/msg/reactjs/Xv9_kVoJJOw/8agybgNhUN4J).

At least it's not working for me.

```javascript
_onMomentumScrollEnd: function(e) {
  // NOTE: `this` is still set to the context of the component containing Swiper 
  //        and not the Swiper component itself.
  console.log(this.state.index);  // logs `undefined`
},
```

The React warning: `Warning: bind(): React component methods may only be bound to the component instance.`

The core team seems to handle callbacks with explicit params and without using `call`, `apply`, or `bind`.

```javascript
this.props.onMomentumScrollEnd && this.props.onMomentumScrollEnd(e, this);
// NOTE: `this.state.index` works as expected although it seems heavy handed to pass `this`

this.props.onMomentumScrollEnd && this.props.onMomentumScrollEnd(e, this.state.index);
// NOTE: would be ideal
```

**Comment by leecade** [comment]
hi @smothers 

```jsx
<Swiper ...
          onMomentumScrollEnd={function(){console.log('this.state.index:', this.state.index)}}
```

```
2015-05-02 14:02:51.547 [info][tid:com.facebook.React.JavaScript] "this.state.index:", 1
2015-05-02 14:02:52.629 [info][tid:com.facebook.React.JavaScript] "this.state.index:", 2
2015-05-02 14:02:53.780 [info][tid:com.facebook.React.JavaScript] "this.state.index:", 3
2015-05-02 14:02:54.945 [info][tid:com.facebook.React.JavaScript] "this.state.index:", 0
```

is this right for you?

And I notice `this.setState` is async, so I call the `onMomentumScrollEnd` in `setTimeout` to ensure synchronous update `index`.

If there is still a problem, tell me, thanks.

**Comment by smothers** [comment]
@leecade 

Returns the index
```javascript
<Swiper ...
  onMomentumScrollEnd={function(){console.log('this.state.index:', this.state.index)}}
```

Returns undefined
```javascript
<Swiper ...
  onMomentumScrollEnd={this._onMomentumScrollEnd}

_onMomentumScrollEnd: function() {
  console.log('this.state.index:', this.state.index)
},
```

**Comment by leecade** [comment]
@smothers I fixed this issue.

Now you can get `state` and `this`(ref to swiper's context) from params, for example:

```jsx
var swiper = React.createClass({
  _onMomentumScrollEnd: function (e, state, context) {
    console.log(state, context.state)
  },
  render: function() {
    return (
      <Swiper style={styles.wrapper}
      onMomentumScrollEnd ={this._onMomentumScrollEnd}
     ...
      </Swiper>
    )
  }
})
```

**Comment by smothers** [comment]
@leecade thanks looks good :trophy:
