### ISSUE TITLE
index.bundle:7664 Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by ycsjqsjz** [leecade/react-native-swiper#750]
不能读取x属性是因为 -swiper 默认播放时间的问题。默认是2.5秒播放完。时间太快了。在swiper的src下面的index.js中171行修改默认的时间。改大一点就好了。继续踩坑中

**Comment by sg552** [comment]
upgrade to 1.5.14  
refer to:https://github.com/leecade/react-native-swiper/issues/582
