### ISSUE TITLE
Cannot assign to read only property 

### ISSUE THREAD

**Issue by leijing7** [leecade/react-native-swiper#77]
Only onMomentumScrollEnd ={this._onMomentumScrollEnd} works as listed in the example. Using other
onMomentumScrollBegin
onTouchStartCapture
onTouchStart
onTouchEnd
onResponderRelease
would have the error described in the title.

**Comment by leijing7** [comment]
I had this problem when I use this module like 

    var Swiper = require('react-native-swiper')

But after I copied the source code out of the node_modules to a local js file  as 

    var Swiper = require('./Swiper.js')

The problem is gone. All props can be signed again. Haven't figured out why.

**Comment by leijing7** [comment]
The below code does not have problem either.

    var Swiper = require('./node_modules/react-native-swiper/src/index.js');

Looks like the npm packaging got problem.

**Comment by leijing7** [comment]
I think this is caused by babel which translated es6 to old js.

**Comment by L-Jovi** [comment]
the same issue

**Comment by tasiyo7333** [comment]
I'm also have the same issue,too.

**Comment by avrame** [comment]
I'm having this issue as well, using Babel.

**Comment by sslash** [comment]
+1

**Comment by seanislegend** [comment]
I can reproduce this error, too.

Furthermore, only the `onMomentumScrollEnd` callback includes `state` and `context` arguments.

**Comment by nazywamsiepawel** [comment]
+1, battling the same issue

**Comment by Kim-Andersen** [comment]
+1
