### ISSUE TITLE
how to hide the dots? set showsButtons to false does not work.

### ISSUE THREAD

**Issue by wangzhenlalala** [leecade/react-native-swiper#776]
### Which OS ?
macOS 10.13.4
### Version
Which versions are you using:

- react-native-swiper 1.5.13
- react-native v0.38.1

### How to reproduce it>
To help us, please fork this component, modify one example in examples folder to reproduce your issue and include link here.
-

### Steps to reproduce
1.
2.
3.

**Comment by joeydeeds** [comment]
`<Swiper
        loop={false}
        showsPagination={false}
      >`

loop false disables the infinite loop

**Comment by YassineGherbi** [comment]
Shouldn't this issue be closed?

**Comment by SSTPIERRE2** [comment]
Yes, the documentation states how to interact with the pagination. Use `showsPagination={false}` to hide the "dots" 😛 
@arribbar

**Comment by Nine-Ball9** [comment]
> Yes, the documentation states how to interact with the pagination. Use `showsPagination={false}` to hide the "dots" 😛
> @arribbar

if i want to off dot at last page, how should i use?

**Comment by kafinsalim** [comment]
my dots didnt show even when i only use default options, 

`
<Swiper style={styles.wrapper}>
        {slideContent.map((item, index) => (
          <Slide key={index} text={item.text} image={item.image} />
        ))}
</Swiper>
`
is this repo is dead?

**Comment by ArrayZoneYour** [comment]
@kafinsalim , are you using the 1.6.0-rc.1 version?

**Comment by kafinsalim** [comment]
Hi, my deps are :
`
"react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-swiper": "^1.5.14"
`

but its solved now, i replace from 
`<View><Image><Swiper><Slide></Swiper><Button/></View>`
to 
`<><Image><Swiper><Slide></Swiper><Button/></>`

idk why but now the dots show. maybe because of the view container style.

**Comment by kafinsalim** [comment]
sorry i was typo i imported different package it was react-native-animation-swiper. my problem solved after using right import and re read documentation. thanks @ArrayZoneYour

**Comment by martinlockett** [comment]
> > Yes, the documentation states how to interact with the pagination. Use `showsPagination={false}` to hide the "dots" 😛
> > @arribbar
> 
> if i want to off dot at last page, how should i use?

```
    <Swiper
          showsPagination={!this.state.isShowingLastScreen}
          onIndexChanged={(index: number) => {
            console.log(`- ${index}`);
            this.setState({ isShowingLastScreen: index === indexOfLastScreen });
          }}
```
