### ISSUE TITLE
How to display second item near to first one?

### ISSUE THREAD

**Issue by kas2000** [leecade/react-native-swiper#783]
Hi everyone. In my project I have to display next item near to the item which is currently displayed. 
When I remove Swiper tag it displays how I want it and I can call it as "Expected version":

<img width="386" alt="screen shot 2018-05-16 at 16 28 39" src="https://user-images.githubusercontent.com/29202543/40111975-556ec274-5926-11e8-8901-2010e1802d13.png">
However, when I add Swiper, it only shows one item:

<img width="391" alt="screen shot 2018-05-16 at 16 31 34" src="https://user-images.githubusercontent.com/29202543/40112080-afbb506c-5926-11e8-8353-61234503ffaa.png">

I've tried to add a negative margin, but it didn't help. Is there any possibilities to implement it?

**Comment by gaoxiaosong1113** [comment]
I have the same problem
