### ISSUE TITLE
Exception 'this.refs.scrollView.scrollTo is not a function'  on android device

### ISSUE THREAD

**Issue by ghostboyzone** [leecade/react-native-swiper#79]
`ViewPagerAndroid` does not have `scrollTo` method

**Comment by ghostboyzone** [comment]
On `android` platform, we can use [onPageSelected](https://facebook.github.io/react-native/docs/viewpagerandroid.html#onpageselected),  [onPageScroll](https://facebook.github.io/react-native/docs/viewpagerandroid.html#onpagescroll)  to call `onPageScroll` and `onPageSelected` method, and then use [setPage](http://facebook.github.io/react-native/docs/viewpagerandroid.html#initialpage) to update index

**Comment by zsf513** [comment]
I have the same problem,can you give me a demo on android.

**Comment by joeyzone** [comment]
ths, I have the same problem, i will try

**Comment by sdg9** [comment]
Facing same problem as well

**Comment by srsolano** [comment]
Same problem here too

**Comment by Bob1993** [comment]
+1

**Comment by ghamaide** [comment]
+1

**Comment by tepamid** [comment]
+1

**Comment by rajkissu** [comment]
Fixed in #112
