### ISSUE TITLE
Npm Package Missing Dependency: react-timer-mixin

### ISSUE THREAD

**Issue by cuongvo** [leecade/react-native-swiper#8]
https://github.com/leecade/react-native-swiper/blob/890c0ce64e2192c2ca7830e6699f67b88171e74b/src/index.js#L20

It appears [react-timer-mixin](https://github.com/reactjs/react-timer-mixin) isn't being included as a dependency and required above.

**Comment by leecade** [comment]
hi @cuongvo 

`react-timer-mixin` is provided by `react-native`.

see: https://github.com/facebook/react-native/blob/master/package.json#L57

I guess you forgot run `react-native init project` before?

Anyway I will improve the problem in README.md later.

**Comment by cuongvo** [comment]
@leecade Thanks for replying! Maybe I'm misunderstanding how npm dependencies work, but what you linked shouldn't resolve the require in your package -- only react-native. I think it's working due to the default packager.

If you use something else to bundle your dependencies and handle transpilation (such as [react-native-webpack-server](https://github.com/mjohnston/react-native-webpack-server)) it looks to break.

**Comment by leoasis** [comment]
:+1: on this, you should specify the dependency now

**Comment by tomtang539** [comment]
I'm having this exact issue at the moment, is there a temporary fix?

**Comment by paulmederos** [comment]
Looks like `react-native` doesn't include `react-timer-mixin` any longer.

@tomtang539 I was able to continue using Swiper by installing `react-timer-mixin` myself, using the command `npm install react-timer-mixin --save` (--save to add it to the package.)

**Comment by guofoo** [comment]
Issue should be re-opened. As @paulmederos mentioned, it needs to be installed manually. This is on react-native 0.11.x
