### ISSUE TITLE
First two child components rendered twice

### ISSUE THREAD

**Issue by MauriiiM** [leecade/react-native-swiper#805]
### Which OS ?
iOS and Android
### Version
Which versions are you using:

- react-native-swiper v1.5.13
- react-native v0.55.4

### Expected behavior
Render each child component of Swiper only once.

### Actual behavior
First 2 child components in Swiper get rendered 2 times. More than 2 back to normal.

I added 2 child component to Swiper. It plays a video when componentDidMount() gets called. I heard more than 2 videos playing. Added a print statement in componentDidMount() and got 4 prints. Doesn't occur when I move the same components outside of Swiper.

### How to reproduce it>
To help us, please fork this component, modify one example in examples folder to reproduce your issue and include link here.
-  Normal use

### Steps to reproduce
1. add swiper component
2. add 2 custom child component with something done in their componentDidMount() (such as a console log)

**Comment by Artkoch** [comment]
I've got the same issue. Is there a workaround?

**Comment by Artkoch** [comment]
As far as I can tell, it renders the first and the last slides two times. The slides in between it renders one time.

**Comment by MauriiiM** [comment]
Yeah, that's correct, I completely forgot about this issue and never updated. It has to render the first and last slides twice when it's looped. I ended up changing how I approached it and didn't set it to loop.

**Comment by Artkoch** [comment]
> Yeah, that's correct, I completely forgot about this issue and never updated. It has to render the first and last slides twice when it's looped. I ended up changing how I approached it and didn't set it to loop.

The way I've solved it was I limited loadMinimalSize to 0, but your approach is much better. Thank you very much.
