### ISSUE TITLE
Active Dot Doesn't Change On Slide For Android

### ISSUE THREAD

**Issue by sritampatnaik** [leecade/react-native-swiper#81]
This is my component https://gist.github.com/sritampatnaik/e888082719a566352a04 with the dots. The active dot stays as the first dot even after swiping.

**Comment by joeyzone** [comment]
yeah, the same error in my project

**Comment by leogeng** [comment]
@ leecade ,
I also have this issue in ios

**Comment by ravirupareliya** [comment]
Same issue with android, did anyone find solution?
