### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by showtan001** [leecade/react-native-swiper#820]
### Version

- react-native-swiper 1.5.10
- react-native 0.51.0

### Error
Error in test environment

![screenshot_2018-07-01-22-13-54-958_com jordina](https://user-images.githubusercontent.com/32892347/42260619-be459e20-7f97-11e8-8dfe-043fb641cf1d.png)

**Comment by ashokkumar88** [comment]
I having same issue when `autoplay={true}`

**Comment by iamdurui** [comment]
I having same issue when autoplay={true}

**Comment by lishiwei** [comment]
I also having same issue when autoplay={true}

**Comment by ashokkumar88** [comment]
In real device I am not getting this error. Only getting in simulator.

**Comment by Tiger-man** [comment]
@showtan001 @ashokkumar88 @iamdurui @lishiwei @andrew 你们最后怎么解决的

**Comment by HighSoftWare96** [comment]
I'm getting the error only when calling scrollBy()

**Comment by showtan001** [comment]
@ashokkumar88 @iamdurui @lishiwei @andrew @Tiger-man  @HighSoftWare96  I ended up using Carousel in teast, which is much better than swiper, especially the image loading speed.

**Comment by sg552** [comment]
for those who met the same problem: https://github.com/leecade/react-native-swiper/issues/582

upgrade to 1.5.14 .
