### ISSUE TITLE
Swiper inside an Animated.View does not work

### ISSUE THREAD

**Issue by NdozHH** [leecade/react-native-swiper#825]
### Which OS ?
Android
### Version
Which versions are you using:

- react-native-swiper 1.5.13?
- react-native v0.55.4

### Expected behaviour

That the swiper manually slides and accepts the onPress events of the touchable component that is in it

### Actual behaviour
Manual sliding does not work and pressing the elements does not work onPress

### How to reproduce it>
To help us, please fork this component, modify one example in examples folder to reproduce your issue and include link here.
-

### Steps to reproduce
1.
2.
3.

**Comment by NdozHH** [comment]
Solved

**Comment by devcocup** [comment]
@NdozHH How did you resolve this?

**Comment by sinclairjaza** [comment]
Any feedback please? I'm still face to this issue
Thanks
