### ISSUE TITLE
autoplay={true} in android error

### ISSUE THREAD

**Issue by joeyzone** [leecade/react-native-swiper#83]
i tried it , delete every keyword, then found autoplay's errror. i used in ios same code success

**Comment by damao1989** [comment]
I have the same problem now.

**Comment by Sean-Snow** [comment]
+1 
     undefined is not a function (evaluating 'this.refs.scrollView.scrollTo(y,x)')
     TimerMixin.js:18
     JSTimers.js:47

**Comment by ghamaide** [comment]
+1

**Comment by mhinc14** [comment]
+1 
undefined is not a function (evaluating 'this.refs.scrollView.scrollTo(y,x)')

**Comment by F2EVarMan** [comment]
+1

**Comment by zccan** [comment]
+1

**Comment by zhoujunhua** [comment]
+1

**Comment by robbinszf** [comment]
+1
