### ISSUE TITLE
first render

### ISSUE THREAD

**Issue by userbq201** [leecade/react-native-swiper#861]
### Which OS ?
android
### Version
Which versions are you using:

- react-native-swiper v1.5.13
- react-native v0.55.3

I  have large list. When navigate render slowly. this task [35](https://github.com/leecade/react-native-swiper/pull/217) not help. Because first render called !. Have 100 page in first render 100 page. And etc

**Comment by navata** [comment]
I have same this issues. I have about 7 pages, each page have list data. In first render, it very long about 8 seconds. I think it have issue when render UI.

**Comment by userbq201** [comment]
@navata use InteractionManager or use react-native-swiper-flatlist. I chose option 2

**Comment by userbq201** [comment]
@navata no. Lagre list only use with flatlist
