### ISSUE TITLE
 horizontal = {false} does not work!!!!

### ISSUE THREAD

**Issue by EvalGitHub** [leecade/react-native-swiper#882]
horizontal = {false} does not work

**Comment by GjMagic** [comment]
me, too. it work in ios, but, it doesn't work in android.

**Comment by EvalGitHub** [comment]
> me, too. it work in ios, but, it doesn't work in android.

 no one can fix it ??

**Comment by EvalGitHub** [comment]
> me, too. it work in ios, but, it doesn't work in android.
mayby you can use "@nart/react-native-swiper"

**Comment by EvalGitHub** [comment]
@nart/react-native-swiper

**Comment by zxymgl** [comment]
I dont find nart/react-native-swiper  .

**Comment by weiweiwoep** [comment]
@nart/react-native-swiper 这个不完善,嵌套ScrollView时,ScrollView无法滚动
