### ISSUE TITLE
Change the width of the slide

### ISSUE THREAD

**Issue by ThomasLarge** [leecade/react-native-swiper#895]
### Version

- react-native-swiper v1.5.13
- react-native v0.57.1

## Slide width

It feels like the slider / item inside the swiper is set to 100% of the width, I need to create a slider that shows 3 images at a time but I'm unable to find a way to do this.

Has anyone done this before? or can help me?

**Comment by ThomasLarge** [comment]
Anyone got an update?

**Comment by ThomasLarge** [comment]
Any update?

**Comment by bexuma** [comment]
I'd like to show one at the center (100% of card's width), and the other two on its sides with 20% of card's width.

**Comment by bexuma** [comment]
This satisfies my request: https://github.com/archriss/react-native-snap-carousel
