### ISSUE TITLE
WebView inside swiper reloads

### ISSUE THREAD

**Issue by subpublicanders** [leecade/react-native-swiper#9]
I'm using a Swiper to wrap a couple of WebViews.
But each time I swipe, the WebView reloads (and scrolls to the top).

**Comment by leecade** [comment]
hi @subpublicanders I think the new version fixed this issue.

> 838b24c Re-design a loop model for avoid img flickering.

If not, make me know i will check it again, thanks

**Comment by subpublicanders** [comment]
Worked like a charm!
I'll be trying the latest each time in the future :)
