### ISSUE TITLE
Disable Swiping

### ISSUE THREAD

**Issue by yamill** [leecade/react-native-swiper#91]
Is there a way to disable swiping?

**Comment by YashYash** [comment]
Hey you can just do scrollEnabled={ false }. Im guessing react-native-swiper is a customized scrollView. It works for me. Hope this helps.

**Comment by yamill** [comment]
great. thanks!

**Comment by SukumarSmart** [comment]
thanks! @YashYash

**Comment by SORNVENGE** [comment]
> Hey you can just do scrollEnabled={ false }. Im guessing react-native-swiper is a customized scrollView. It works for me. Hope this helps.

How to disable swip back or we can say swip left with react-native-swiper ?

**Comment by VienLeVan** [comment]
> Hey you can just do scrollEnabled={ false }. Im guessing react-native-swiper is a customized scrollView. It works for me. Hope this helps.

Thanks

**Comment by hoangsang0109** [comment]
Thanks @YashYash

**Comment by jonathanmachado** [comment]
How to disable swip back or we can say swip left with react-native-swiper ?

**Comment by joebengos** [comment]
How to disable the siwper to the right or left?

**Comment by thangpq** [comment]
> How to disable the siwper to the right or left?

hide them then your swip will under your control.
it is nice component, really easy to use. You can set current slide or do anything you want.

```
        showsButtons={false}
        showsPagination={false}>
```
