### ISSUE TITLE
scrollBy method definition is missing on Swiper

### ISSUE THREAD

**Issue by danielholmes** [leecade/react-native-swiper#930]
### Which OS ?
iOS

### Version
Which versions are you using:

- react-native-swiper v1.5.14
- react-native v0.57.8

### Expected behaviour

Using scrollBy on a Swiper typed instance passes TypeScript compilation

### Actual behaviour

It doesn't (says scrollBy does not exist on type Swiper)

### How to reproduce it
```ts
import Swiper from 'react-native-swiper'

const swiper: Swiper = new Swiper({})
if (swiper) {
  swiper.scrollBy(1, false)
}
```

### Steps to reproduce
1. Run the above code through the TypeScript compiler

**Comment by retyui** [comment]
https://github.com/leecade/react-native-swiper/issues/713
