### ISSUE TITLE
How can i change the dots and buttons position?

### ISSUE THREAD

**Issue by JonasOmdal** [leecade/react-native-swiper#935]
Current:
![help](https://user-images.githubusercontent.com/25055755/52849045-77c2be80-3110-11e9-9669-4c71675a812f.jpg)

I need some help with customizing on the swiper. Is it possible to move the dots and buttons up to the text area?
Like this: 
![help kopi](https://user-images.githubusercontent.com/25055755/52849086-8610da80-3110-11e9-8d9c-d3ecd0060283.jpg)

And how can i change the color on the buttons?

**Comment by sonicvision** [comment]
This was closed. Any idea how is this to be achieved?

**Comment by jacek213** [comment]
bump

**Comment by Billydubb** [comment]
So the `paginationStyle` prop refers to the pagination container. What worked for me was to set `top: 0` and `alignItems: "flex-start"` (since the pagination container by default has `flexDirection: "row"`). And then apply paddings to your liking
