### ISSUE TITLE
scrollTo method changed in React Native 0.20.0

### ISSUE THREAD

**Issue by nodkrot** [leecade/react-native-swiper#95]
`scrollTo(y, x, animated)` is deprecated. Use `scrollTo({x: 5, y: 5, animated: true})` instead.

**Comment by edagarli** [comment]
I also encountered the same problem

**Comment by rainer-liao** [comment]
same problem

**Comment by lrettig** [comment]
+1

**Comment by Kennytian** [comment]
+1

**Comment by jw84** [comment]
Only happens when autoplay={true}

**Comment by lrettig** [comment]
I didn't specify autoplay (and it defaults to false), and this is still happening to me--not when I swipe, but when I tap on the next button.

**Comment by fungilation** [comment]
This warning in log also shows when showsButtons=true, and user tap on either prev or next buttons.
