### ISSUE TITLE
JSON value '3' of type NSNumber cannot be converted to CGSize

### ISSUE THREAD

**Issue by Ravi448** [leecade/react-native-swiper#955]
Getting this error while added MapView inside swiper.
![image](https://user-images.githubusercontent.com/29150136/54683799-9b768b80-4b38-11e9-9c3c-c7c7c855434d.png)

Full error:

JSON value '3' of type NSNumber cannot be converted to CGSize

convertCGStruct
    RCTConvert.m:444
+[RCTConvert CGSize:]
__invoking___
-[NSInvocation invoke]
__createNSInvocationSetter_block_invoke
__49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke.162
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke_2
RCTPerformBlockWithLogFunction
RCTPerformBlockWithLogPrefix
__49-[RCTComponentData propBlockForKey:isShadowView:]_block_invoke
__37-[RCTComponentData setProps:forView:]_block_invoke
-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]
-[RCTComponentData setProps:forView:]
__50-[RCTUIManager createView:viewName:rootTag:props:]_block_invoke.467
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.544
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

Tried to set every prop but still not working.
there are total 4 swipe screen, 1st one is map view and rest are simple screens.
`<Swiper 
        showsButtons={true}
        index={0}
        loop={false}
        nextButton={<Text style={{fontSize:20,color:colors.colorPrimary,backgroundColor:'#fff',paddingHorizontal:10,paddingVertical:10,borderRadius:5}}>{translate('next')}</Text>}
        prevButton={<Text style={{fontSize:20,color:colors.colorPrimary}}> {translate('previous')} </Text>}
        scrollEnabled={false}
        buttonWrapperStyle={{backgroundColor: 'transparent', flexDirection: 'row', position: 'absolute', bottom: 0, left: 0, flex: 1, paddingHorizontal: 10, paddingVertical: 10, justifyContent: 'space-between', alignItems: 'flex-end'}}
        activeDotColor={colors.colorPrimary}
        loadMinimal={true}
        loadMinimalSize={3}
        dot={<View style={{backgroundColor:'rgba(0,0,0,.2)', width: 8, height: 8,borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 0}} />}
        activeDot={<View style={{backgroundColor:colors.colorPrimary, width: 8, height: 8,borderRadius: 4, marginLeft: 3, marginRight: 3, marginTop: 3, marginBottom: 0}} />}
        >`

**Comment by anastely** [comment]
@Ravi448  are you solve it?

**Comment by Ravi448** [comment]
@anastely It was a type error. I had mistakenly converted string into number. 
Basically I had an input and that was taking number inputs, but I entered string input in that input. That was the mistake.

**Comment by Ravi448** [comment]
I think I should close this issue.

**Comment by ashwingattani** [comment]
@Ravi448 can you explain how you reached to the code in error? I am not able to find the pain point in my code.

**Comment by Ravi448** [comment]
Basically I had swiper in my app. In the last screen of swiper, I got the error, then I investigated each component in last screen and found the exact error. It took me 1 week to trace the error 😸

**Comment by Ravi448** [comment]
@ashwingattani Basically I had swiper in my app. In the last screen of swiper, I got the error, then I investigated each component in last screen and found the exact error. It took me 1 week to trace the error 😸

**Comment by abrahamtambac** [comment]
Sorry for really late reply, It causing by Stylesheet in your project, the way that I used to find the value has been informed which in this case is error.

**Comment by snaveware** [comment]
Struggled with the problem for a day.
I found out that I when creating a card Component with box shadows, I set the value for 'shadowOffset' property as a number 10, instead of an object 
eg. shadowOffset: {width: -2, height: 10},
