### ISSUE TITLE
How to disable next and prev button from swipper in react native.I just want to display dots for navigation

### ISSUE THREAD

**Issue by lovesharma1995** [leecade/react-native-swiper#970]
this is what I tried so far and here swiperButtons state set to false.
<Swiper 
            showsButtons={this.state.swiperButtons} showsPagination={this.state.swiperButtons} 
            index={this.state.index}>
              {eventsData}
</Swiper>

**Comment by retyui** [comment]
This repo dead: https://github.com/leecade/react-native-swiper/issues/713

**Comment by JhowEMK** [comment]
Try set prop 'showsButtons={false}' and 'showsPagination={true}', works for me!

**Comment by lovesharma1995** [comment]
> Try set prop 'showsButtons={false}' and 'showsPagination={true}', works for me!

yeah, it worked for me as well.
