### ISSUE TITLE
ViewPagerAndroid err

### ISSUE THREAD

**Issue by logictuLuoqi** [leecade/react-native-swiper#973]
### Version
Which versions are you using:

- react-native-swiper v1.5.6
- react-native v0.5.9

### Expected behaviour

console.error

ViewPagerAndroid has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native'. See https://github.com/react-native-community/react-native-viewpager

**Comment by sintylapse** [comment]
@logictuLuoqi why is this closed? it seems react-native-swiper should use @react-native-community/async-storage now

**Comment by hu-qi** [comment]
Hello！
Has your problem been solved?
