### ISSUE TITLE
containerStyle prop is missed in typescript typings

### ISSUE THREAD

**Issue by Eward-Wang** [leecade/react-native-swiper#974]
### Version
Which versions are you using:

- react-native-swiper v1.5.14
- react-native v0.59

### Actual behaviour

![image](https://user-images.githubusercontent.com/8791349/56940670-65b6c080-6b42-11e9-86a9-43d70250db11.png)

**Comment by Eward-Wang** [comment]
```js
// Interim solution
const SwiperT: ComponentType<
  SwiperProps & {
    containerStyle?: StyleProp<ViewStyle>;
  }
> = Swiper;
```

**Comment by retyui** [comment]
This repo dead: https://github.com/leecade/react-native-swiper/issues/713
Your issue is like other 480+ issues, will not be resolved in the short term.
