### ISSUE TITLE
Newest version of react-native will extract ViewPagerAndroid

### ISSUE THREAD

**Issue by rnjssh96** [leecade/react-native-swiper#992]
I get the warning that says ViewPagerAndroid has been extracted from release. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native' core. So I hope this case is considered too.

**Comment by rewdt** [comment]
This has been popping up more frequently. I would really appreciate if this is looked into. Thanks

**Comment by rewdt** [comment]
Do you accept PR's I haven' done much. but I can look through and contribute. This plugin has really been helpful in my react-native career and I would hate to see it go to waste

**Comment by ArrayZoneYour** [comment]
Thanks for your feedback, #997 Solved.
